/**
 * Vendor-neutral credential-proxy wiring for spawned coding sub-agents
 * (#11536 E3 — the NON-MODEL sibling of the E2 model-gateway path).
 *
 * When `ELIZA_CREDENTIAL_PROXY_URL` + `ELIZA_CREDENTIAL_PROXY_TOKEN` are set, a
 * spawned coding agent must be able to `git push` with ZERO raw PAT in its
 * env. This module:
 *   1. deletes every raw VCS credential from the assembled child env (or, in
 *      strict mode, refuses the spawn — the fail-closed guard), as a clearly
 *      separate block from E2's model-key deletes so the two lanes merge
 *      cleanly;
 *   2. injects the proxy config the git credential helper needs;
 *   3. materializes a dependency-free git credential helper and points the
 *      child's git config at it via `GIT_CONFIG_*` env — so git obtains a
 *      broker-minted credential at push time and no PAT is ever in the env.
 *
 * The helper is a self-contained Node script (node built-ins only) so it runs
 * inside a child coding agent that may not resolve `@elizaos/core`. Its request
 * signing MUST stay byte-for-byte identical to
 * `buildCredentialProxyCanonicalString` / `signCredentialProxyRequest` in
 * `@elizaos/core`; `credential-proxy-env.test.ts` pins that with a cross-check.
 *
 * @module services/credential-proxy-env
 */

import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  CREDENTIAL_PROXY_RAW_PAT_VARS,
  CREDENTIAL_PROXY_SIGNING_KEY_KEY,
  CREDENTIAL_PROXY_TOKEN_KEY,
  CREDENTIAL_PROXY_URL_KEY,
  type CredentialProxyConfig,
  CredentialProxyStrictError,
  resolveCredentialProxyConfig,
  resolveStateDir,
} from "@elizaos/core";
import { readConfigEnvKey } from "./config-env.js";

/** Comma-separated git hosts the helper will broker credentials for. */
export const CREDENTIAL_PROXY_GIT_HOSTS_KEY =
  "ELIZA_CREDENTIAL_PROXY_GIT_HOSTS";

/** Resolve the active proxy config from the config-env (config file over process env). */
export function resolveOrchestratorCredentialProxyConfig():
  | CredentialProxyConfig
  | undefined {
  return resolveCredentialProxyConfig((key) => readConfigEnvKey(key));
}

/**
 * The git credential helper source. Dependency-free (node:crypto + global
 * fetch + process/stdin only). git invokes it as `<helper> <operation>` with
 * the request on stdin (`protocol=`, `host=`, `path=`, blank line). On `get`
 * for an allowlisted https host it POSTs a signed request to the proxy's
 * `/git-credential` endpoint and prints the broker-minted `username`/`password`
 * back to git. `store`/`erase` are no-ops (the proxy owns the credential).
 *
 * Kept in lockstep with `@elizaos/core`'s canonical signing scheme:
 *   eliza-credential-proxy-v1 \n METHOD \n host \n pathAndSearch \n ts \n bodyHashHex
 */
export const GIT_CREDENTIAL_PROXY_HELPER_SOURCE = [
  "#!/usr/bin/env node",
  "// Auto-generated by @elizaos/plugin-agent-orchestrator (#11536 E3).",
  "// Self-contained git credential helper: brokers auth through the eliza",
  "// credential proxy so `git push` needs no raw PAT in the environment.",
  'import { createHash, createHmac } from "node:crypto";',
  "",
  "const op = process.argv[2];",
  'const url = (process.env.ELIZA_CREDENTIAL_PROXY_URL || "").trim();',
  'const token = (process.env.ELIZA_CREDENTIAL_PROXY_TOKEN || "").trim();',
  'const signingKey = (process.env.ELIZA_CREDENTIAL_PROXY_SIGNING_KEY || "").trim();',
  'const hosts = (process.env.ELIZA_CREDENTIAL_PROXY_GIT_HOSTS || "")',
  '  .split(",").map((h) => h.trim().toLowerCase()).filter(Boolean);',
  "",
  "function fail(msg) {",
  '  process.stderr.write("[git-credential-eliza-proxy] " + msg + "\\n");',
  "  process.exit(1);",
  "}",
  "",
  "async function readStdin() {",
  '  let data = "";',
  '  process.stdin.setEncoding("utf8");',
  "  for await (const chunk of process.stdin) data += chunk;",
  "  return data;",
  "}",
  "",
  "function parse(input) {",
  "  const out = {};",
  '  for (const line of input.split("\\n")) {',
  '    const i = line.indexOf("=");',
  "    if (i > 0) out[line.slice(0, i)] = line.slice(i + 1);",
  "  }",
  "  return out;",
  "}",
  "",
  "async function main() {",
  "  // Only `get` returns a credential; `store`/`erase` are handled by the proxy.",
  '  if (op !== "get") return;',
  '  if (!url || !token) fail("credential proxy is not configured");',
  "  const req = parse(await readStdin());",
  '  const host = (req.host || "").toLowerCase();',
  '  const protocol = (req.protocol || "").toLowerCase();',
  '  if (protocol !== "https") fail("refusing non-https protocol: " + protocol);',
  '  if (!hosts.includes(host)) fail("host not on credential-proxy allowlist: " + host);',
  "",
  '  const body = JSON.stringify({ host, protocol, path: req.path || "" });',
  "  const timestamp = String(Math.floor(Date.now() / 1000));",
  '  const bodyHash = createHash("sha256").update(body).digest("hex");',
  "  const canonical = [",
  '    "eliza-credential-proxy-v1",',
  '    "POST",',
  "    host,",
  '    "/git-credential",',
  "    timestamp,",
  "    bodyHash,",
  '  ].join("\\n");',
  "",
  "  const headers = {",
  '    "content-type": "application/json",',
  '    authorization: "Bearer " + token,',
  '    "x-eliza-proxy-target": "https://" + host,',
  '    "x-eliza-proxy-timestamp": timestamp,',
  "  };",
  "  if (signingKey) {",
  '    const mac = createHmac("sha256", signingKey).update(canonical).digest("hex");',
  '    headers["x-eliza-proxy-signature"] = "v1=" + mac;',
  "  }",
  "",
  '  const endpoint = url.replace(/\\/+$/, "") + "/git-credential";',
  "  let res;",
  "  try {",
  '    res = await fetch(endpoint, { method: "POST", headers, body });',
  "  } catch (e) {",
  '    return fail("proxy request failed: " + (e && e.message ? e.message : e));',
  "  }",
  '  if (!res.ok) fail("proxy returned " + res.status);',
  "  const cred = await res.json();",
  '  if (!cred || !cred.password) fail("proxy did not return a credential");',
  '  const username = cred.username || "x-access-token";',
  '  process.stdout.write("protocol=" + protocol + "\\n");',
  '  process.stdout.write("host=" + host + "\\n");',
  '  process.stdout.write("username=" + username + "\\n");',
  '  process.stdout.write("password=" + cred.password + "\\n");',
  "}",
  "",
  "main().catch((e) => fail(e && e.message ? e.message : String(e)));",
  "",
].join("\n");

let cachedHelperPath: string | undefined;

/**
 * Materialize the git credential helper to a stable, child-readable path and
 * return it. Idempotent: the content is static, so it is written once per
 * process and reused. Materialized from an embedded string (not a shipped
 * file) so it works identically in dev, npm, and bundled installs.
 */
export function materializeGitCredentialHelper(): string {
  if (cachedHelperPath) return cachedHelperPath;
  const dir = join(resolveStateDir(), "credential-proxy");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "git-credential-proxy-helper.mjs");
  writeFileSync(path, GIT_CREDENTIAL_PROXY_HELPER_SOURCE, "utf8");
  chmodSync(path, 0o700);
  cachedHelperPath = path;
  return path;
}

/** Test hook: drop the memoized helper path so a test can re-materialize. */
export function _resetCredentialProxyHelperCache(): void {
  cachedHelperPath = undefined;
}

/**
 * Rewrite an assembled sub-agent env for credential-proxy mode. Runs as its
 * own block in `AcpService.buildEnv`, independent of the E2 model-gateway
 * rewrite (distinct env keys). Deletes every raw VCS credential first, then
 * injects the proxy config + git credential helper wiring.
 *
 * Fail-closed: in strict mode a raw PAT present in the assembled env throws
 * `CredentialProxyStrictError`, which refuses the spawn.
 */
export function applyCredentialProxyEnv(
  env: NodeJS.ProcessEnv,
  config: CredentialProxyConfig,
  nodeExecPath: string,
  options?: { strictScanEnv?: NodeJS.ProcessEnv },
): void {
  // --- fail-closed strict guard + delete-first discipline ---------------
  // Separate from E2's MODEL_GATEWAY_EXCLUDED_PROVIDER_KEYS block: those are
  // model-provider keys, these are VCS PATs. Kept independent so the two
  // #11536 lanes never touch the same lines.
  //
  // Strict mode mirrors E1's "refuse to boot if a raw key is ALSO present":
  // scan the PARENT env (a PAT there is a misconfiguration even though the
  // forwarding deny-list already keeps it out of the child) and refuse the
  // spawn. Non-strict just deletes any PAT that reached the child env.
  const strictScan = options?.strictScanEnv ?? env;
  for (const key of CREDENTIAL_PROXY_RAW_PAT_VARS) {
    if (config.strict) {
      const scanned = strictScan[key];
      if (typeof scanned === "string" && scanned.length > 0) {
        throw new CredentialProxyStrictError(key);
      }
    }
    delete env[key];
  }

  // --- inject proxy config the helper reads -----------------------------
  env[CREDENTIAL_PROXY_URL_KEY] = config.url;
  env[CREDENTIAL_PROXY_TOKEN_KEY] = config.token;
  if (config.signingKey) {
    env[CREDENTIAL_PROXY_SIGNING_KEY_KEY] = config.signingKey;
  } else {
    delete env[CREDENTIAL_PROXY_SIGNING_KEY_KEY];
  }
  const gitHosts = Array.from(new Set(config.routes.map((r) => r.host)));
  env[CREDENTIAL_PROXY_GIT_HOSTS_KEY] = gitHosts.join(",");

  // --- point git at the credential helper via GIT_CONFIG_* --------------
  // An empty credential.helper first resets any helper inherited from the
  // child's ~/.gitconfig, so ours is the only one consulted for the target
  // hosts. Values are shell-quoted (git runs a `!`-prefixed helper via sh).
  const helperPath = materializeGitCredentialHelper();
  const helperValue = `!'${nodeExecPath}' '${helperPath}'`;
  env.GIT_CONFIG_COUNT = "2";
  env.GIT_CONFIG_KEY_0 = "credential.helper";
  env.GIT_CONFIG_VALUE_0 = "";
  env.GIT_CONFIG_KEY_1 = "credential.helper";
  env.GIT_CONFIG_VALUE_1 = helperValue;
}
