// ---------------------------------------------------------------------------
// Chat types — Conversation*, Chat*, Message*, Stream*, Action*, Emote*,
// Document*, Memory*, MCP*, Share*
// ---------------------------------------------------------------------------

import type { LinkedAccountProviderId } from "@elizaos/shared";
import type {
  ConversationMetadata,
  ConversationScope,
} from "./client-types-core";

// Conversations
export interface Conversation {
  id: string;
  title: string;
  roomId: string;
  metadata?: ConversationMetadata;
  createdAt: string;
  updatedAt: string;
}

export interface ConversationGreeting {
  text: string;
  agentName: string;
  generated: boolean;
  persisted?: boolean;
  localInference?: LocalInferenceChatMetadata;
}

export interface CreateConversationOptions {
  includeGreeting?: boolean;
  bootstrapGreeting?: boolean;
  lang?: string;
  metadata?: ConversationMetadata;
}

export type { ConversationMetadata, ConversationScope };

// ── A2UI Content Blocks (Agent-to-UI) ────────────────────────────────

/** A plain text content block. */
export interface TextBlock {
  type: "text";
  text: string;
}

/** An inline config form block — renders ConfigRenderer in chat. */
export interface ConfigFormBlock {
  type: "config-form";
  pluginId: string;
  pluginName?: string;
  schema: Record<string, unknown>;
  hints?: Record<string, unknown>;
  values?: Record<string, unknown>;
}

/** A UiSpec interactive UI block extracted from agent response. */
export interface UiSpecBlock {
  type: "ui-spec";
  spec: Record<string, unknown>;
  raw?: string;
}

/** Union of all content block types. */
export type ContentBlock = TextBlock | ConfigFormBlock | UiSpecBlock;

/** An image attachment to send with a chat message. */
export interface ImageAttachment {
  /** Base64-encoded image data (no data URL prefix). */
  data: string;
  mimeType: string;
  name: string;
  /**
   * Optional client-generated downscaled preview (base64, no prefix). The
   * server persists it separately and exposes it as the attachment's
   * `thumbnailUrl` so the chat tile loads a small image while the full
   * resolution opens in the lightbox.
   */
  thumbnail?: { data: string; mimeType: string };
  /**
   * The stored {@link Transcript} record id when this attachment is a saved
   * transcript — lets the chat tile re-open the rich, editable record.
   */
  transcriptId?: string;
}

/**
 * Media kind for a rendered message attachment. Values match `@elizaos/core`
 * `ContentType` so server payloads line up without pulling core into the
 * browser bundle.
 */
export type MessageAttachmentContentType =
  | "image"
  | "video"
  | "audio"
  | "document"
  | "link";

/**
 * A media attachment carried on a rendered chat message — either uploaded by
 * the user or generated by the agent. Mirrors the `@elizaos/core` `Media`
 * shape (id/url/contentType/title/description/source/text). `url` is a served
 * URL (`/api/media/<hash>`), a remote https URL, or a `data:` URL; the
 * renderer treats all three the same.
 */
export interface MessageAttachment {
  id: string;
  url: string;
  contentType?: MessageAttachmentContentType;
  title?: string;
  description?: string;
  source?: string;
  /** Readable extracted content (transcript / OCR / document text). */
  text?: string;
  /** MIME type when known, e.g. "image/png" or "application/pdf". */
  mimeType?: string;
  /** Downscaled preview URL for the inline tile; `url` is the full original. */
  thumbnailUrl?: string;
  /**
   * The stored {@link Transcript} record id when this attachment is a saved
   * transcript — the chat tile opens it in the maximized, editable viewer.
   */
  transcriptId?: string;
}

export interface ConversationMessageReaction {
  emoji: string;
  count: number;
  users?: string[];
}

export type ChatFailureKind =
  | "insufficient_credits"
  | "no_provider"
  | "provider_issue"
  | "rate_limited"
  | "local_inference";

export interface ChatActionResultSummary {
  actionName?: string;
  success: boolean;
  text?: string;
  error?: string;
  values?: Record<string, unknown>;
}

export type LocalInferenceChatStatus =
  | "missing"
  | "downloading"
  | "loading"
  | "failed"
  | "no_space"
  | "idle"
  | "ready"
  | "cancelled"
  | "routing";

export interface LocalInferenceChatMetadata {
  intent?:
    | "retry"
    | "resume"
    | "redownload"
    | "download"
    | "cancel"
    | "switch_smaller"
    | "status"
    | "use_cloud"
    | "use_local";
  status: LocalInferenceChatStatus;
  modelId?: string | null;
  activeModelId?: string | null;
  provider?: string;
  error?: string;
  progress?: {
    percent?: number;
    receivedBytes: number;
    totalBytes: number;
    bytesPerSec?: number;
    etaMs?: number | null;
  };
}

export type SensitiveRequestStatus =
  | "pending"
  | "saved"
  | "submitted"
  | "fulfilled"
  | "expired"
  | "cancelled"
  | "failed";

export interface SensitiveRequestDelivery {
  mode:
    | "inline_owner_app"
    | "cloud_authenticated_link"
    | "tunnel_authenticated_link"
    | "private_dm"
    | "public_link"
    | "dm_or_owner_app_instruction";
  instruction?: string;
  privateRouteRequired?: boolean;
  canCollectValueInCurrentChannel?: boolean;
  /**
   * Present only when this secret request collects a credential for a blocked
   * coding sub-agent. Identifiers only — the scoped token and the value are
   * NEVER serialized here. When set, `SensitiveRequestBlock` tunnels the value
   * to the waiting child via `client.tunnelCredential` instead of writing it to
   * the agent secret store (the two paths are mutually exclusive).
   */
  tunnel?: {
    credentialScopeId: string;
    childSessionId: string;
    keys?: readonly string[];
  };
}

export interface SensitiveRequestFormField {
  name: string;
  label?: string;
  input?: "secret" | "text" | "image" | "file";
  required?: boolean;
  /** For `input: "image" | "file"` — accepted MIME types (the `accept` attr). */
  mimeTypes?: string[];
  /** For `input: "image" | "file"` — max upload size in bytes. */
  maxBytes?: number;
}

/**
 * `kind: "secret"` — render a per-field password/text form (today's behavior).
 * `kind: "oauth"`  — render a single "Connect …" button that opens the
 * authorization URL in a popup; the actual token never flows through the
 * chat message stream. `fields` is unused for OAuth; the relevant fields are
 * `provider`, `scopes`, and `authorizationUrl`.
 * `kind: "remote_connect"` — render the same per-field text/secret form as
 * `secret`, but on submit dispatch the hardened `CONNECT_EVENT` (point the app
 * at a remote agent) instead of writing the values to the secret store. Used
 * by first-run to collect a remote agent's URL + access token inline.
 */
export interface SensitiveRequestForm {
  type: "sensitive_request_form";
  kind: "secret" | "oauth" | "remote_connect";
  mode: SensitiveRequestDelivery["mode"];
  fields: SensitiveRequestFormField[];
  submitLabel?: string;
  statusOnly?: boolean;
  /** OAuth-only: human-readable provider label (e.g. "GitHub"). */
  provider?: string;
  /** OAuth-only: scopes the consent screen will request. */
  scopes?: string[];
  /**
   * OAuth-only: the consent URL to open. The widget opens this in a popup
   * and never includes it in the rendered chat text. The OAuth callback
   * lands the token in the vault server-side; the widget polls the
   * `secretRequest.status` via `client.getSensitiveRequestStatus` (or
   * receives a fresh `secretRequest` on the next assistant turn).
   */
  authorizationUrl?: string;
}

export interface ConversationSecretRequest {
  key: string;
  reason?: string;
  status: SensitiveRequestStatus;
  delivery?: SensitiveRequestDelivery;
  form?: SensitiveRequestForm;
}

/**
 * Structured "connect another account" request emitted by the agent when the
 * user asks to add/log into an additional Claude or Codex account. The renderer
 * turns this into an inline entry point (per-provider count + "Add account")
 * that opens the existing, already-audited `AddAccountDialog` OAuth/API-key
 * flow — the block never manages accounts itself, it only offers a shortcut
 * into the canonical dialog. Round-trips on the assistant turn the same way
 * `failureKind` does so it survives a GET /messages reload.
 */
export interface AccountConnectRequest {
  /** Providers the user may connect a new account for (offer order preserved). */
  providers: LinkedAccountProviderId[];
  /** Optional short reason the agent surfaced this (e.g. "you asked to add a second Claude account"). */
  reason?: string;
}

export interface ConversationMessage {
  id: string;
  role: "user" | "assistant";
  text: string;
  timestamp: number;
  /** Structured content blocks (A2UI). When present, `text` is the fallback. */
  blocks?: ContentBlock[];
  /**
   * Media attached to this message — user uploads (images/audio/video/pdf) and
   * agent-generated media (images, audio clips). Rendered inline by
   * `MessageAttachments`. Sourced from the message's `content.attachments` on
   * the server and from the SSE `done` event for in-flight assistant turns.
   */
  attachments?: MessageAttachment[];
  /** Source channel when forwarded from another channel (e.g. "autonomy"). */
  source?: string;
  /**
   * Short topic labels extracted for this turn (Stage-1 `topics`). Drives the
   * transcript topic grouping + chips bar (#8928). Absent when the turn had no
   * salient topic.
   */
  topics?: string[];
  /** Concrete action name that produced this assistant turn, when applicable. */
  actionName?: string;
  /** Callback/status lines emitted while the action was running. */
  actionCallbackHistory?: string[];
  /** Username of the sender (e.g. viewer username, discord username). */
  from?: string;
  /** Connector username/handle when available. */
  fromUserName?: string;
  /** Sender avatar URL when the connector can provide one. */
  avatarUrl?: string;
  /** Internal message id this message replies to, when available. */
  replyToMessageId?: string;
  /** Best-effort display name of the replied-to sender. */
  replyToSenderName?: string;
  /** Best-effort username/handle of the replied-to sender. */
  replyToSenderUserName?: string;
  /** Aggregated reactions attached to this message. */
  reactions?: ConversationMessageReaction[];
  /** True when the SSE stream was interrupted before receiving a "done" event. */
  interrupted?: boolean;
  /**
   * Agent reasoning/thought for this turn, rendered as a collapsed-by-default
   * block separate from `text`. Sourced from the SSE `done` event's `thought`
   * field; absent when the model emitted no reasoning.
   */
  reasoning?: string;
  /**
   * When set, this assistant turn is the server's no-provider /
   * provider-issue / insufficient-credits fallback. The renderer can
   * substitute a structured gate UI (e.g. "Connect a provider →
   * Settings") for `failureKind === "no_provider"` instead of rendering
   * the fallback `text` as a normal reply bubble.
   */
  failureKind?: ChatFailureKind;
  /** Structured local-inference status returned with local model command/error replies. */
  localInference?: LocalInferenceChatMetadata;
  /** Structured sensitive/private information request metadata. */
  secretRequest?: ConversationSecretRequest;
  /**
   * Structured "connect another account" request. When set, this assistant
   * turn offers to add another Claude/Codex account: the renderer substitutes
   * the `AccountConnectBlock` (per-provider count + "Add account" opening
   * `AddAccountDialog`) for the plain reply text.
   */
  accountConnect?: AccountConnectRequest;
  /**
   * Voice speaker attribution carried back from the server when this turn was
   * captured via voice and R2's speaker-id pipeline labelled it. Populated by
   * the runtime's voice ingress path; absent for text turns and assistant
   * responses. Mirrors the `ChatVoiceSpeaker` shape consumed by the chat
   * renderer.
   */
  voiceSpeaker?: {
    entityId?: string;
    name?: string;
    userName?: string;
    isOwner?: boolean;
  };
}

/**
 * Runtime guard for a {@link ConversationMessage} — validates the four required
 * fields (`id`, `role`, `text`, `timestamp`) of an untrusted value before it is
 * trusted as a message. Server/connector responses (e.g. `sendInboxMessage`)
 * are appended straight into the rendered message list; a malformed payload
 * (missing id/role/timestamp, an unexpected role) must NOT be `as`-cast into
 * state where it breaks keying/rendering. Use this at the API boundary instead
 * of `value as ConversationMessage`.
 */
export function isConversationMessage(
  value: unknown,
): value is ConversationMessage {
  if (typeof value !== "object" || value === null) return false;
  const m = value as Record<string, unknown>;
  return (
    typeof m.id === "string" &&
    m.id.length > 0 &&
    (m.role === "user" || m.role === "assistant") &&
    typeof m.text === "string" &&
    typeof m.timestamp === "number" &&
    Number.isFinite(m.timestamp)
  );
}

/** One keyword-search hit from `GET /api/conversations/messages/search`. */
export interface ConversationMessageSearchResult {
  messageId: string;
  conversationId: string;
  roomId: string;
  role: "user" | "assistant";
  text: string;
  /** A `…keyword…` excerpt around the first match, for the result row. */
  snippet: string;
  createdAt: number;
  /** Relevance score (higher = better); the server sorts by it then recency. */
  score: number;
}

export interface ConversationMessageSearchResponse {
  results: ConversationMessageSearchResult[];
  count: number;
}

export type ConversationChannelType =
  | "DM"
  | "GROUP"
  | "VOICE_DM"
  | "VOICE_GROUP"
  | "API";

export interface ChatTokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  llmCalls?: number;
  model?: string;
}

/**
 * The discrete phases an in-flight assistant turn moves through, surfaced to the
 * UI so the chat shows what the agent is *doing* (not just breathing dots).
 *
 * - `thinking`   — the turn started; the model is being prompted but no visible
 *                  text has streamed yet.
 * - `streaming`  — the model is emitting the user-visible reply token-by-token.
 * - `running_action` — a concrete action handler is executing (carry
 *                  `actionName`, e.g. "SEND_MESSAGE").
 * - `running_tool`   — a tool/MCP call is running (carry `toolName`).
 * - `evaluating` — post-response evaluators are running.
 * - `waking`     — a non-running cloud agent is auto-resuming (HTTP 202 +
 *                  Retry-After); the request is parked until it answers.
 * - `speaking`   — the reply is being spoken aloud (voice output); client-derived.
 *
 * Emitted by the server as additive SSE `{ type: "status", ... }` events and/or
 * derived client-side. The `token` / `done` / `error` SSE contract is unchanged.
 */
export interface ChatTurnStatus {
  kind:
    | "thinking"
    | "streaming"
    | "running_action"
    | "running_tool"
    | "evaluating"
    | "waking"
    | "speaking";
  /** Optional short human-readable label override for the phase. */
  label?: string;
  /** Canonical action name when `kind === "running_action"`. */
  actionName?: string;
  /** Tool/MCP name when `kind === "running_tool"`. */
  toolName?: string;
}

// Document / Character Knowledge types
export interface DocumentStats {
  documentCount: number;
  fragmentCount: number;
  agentId: string;
}

export type DocumentScope =
  | "global"
  | "owner-private"
  | "user-private"
  | "agent-private";

export type DocumentProvenanceKind =
  | "upload"
  | "learned"
  | "character"
  | "url"
  | "youtube"
  | "bundled"
  | "unknown";

export interface DocumentProvenance {
  kind: DocumentProvenanceKind;
  label: string;
  detail?: string;
}

export interface DocumentRecord {
  id: string;
  filename: string;
  contentType: string;
  fileSize: number;
  createdAt: number;
  fragmentCount: number;
  scope?: DocumentScope;
  scopedToEntityId?: string;
  addedBy?: string;
  addedByRole?: "OWNER" | "ADMIN" | "USER" | "AGENT" | "RUNTIME";
  addedFrom?: string;
  source: DocumentProvenanceKind;
  url?: string;
  provenance: DocumentProvenance;
  canEditText: boolean;
  editabilityReason?: string;
  canDelete: boolean;
  deleteabilityReason?: string;
  content?: { text?: string };
  /** When this document mirrors a voice Transcript (#8789): the original
   *  transcript record id (the Knowledge view links back to it) + its audio. */
  transcriptId?: string;
  transcriptAudioUrl?: string;
}

export interface DocumentDetail extends DocumentRecord {
  content?: { text?: string };
}

export interface DocumentsResponse {
  documents: DocumentRecord[];
  total: number;
  limit: number;
  offset: number;
}

export interface DocumentFragmentRecord {
  id: string;
  text: string;
  position?: number;
  createdAt: number;
}

export interface DocumentFragmentsResponse {
  documentId: string;
  fragments: DocumentFragmentRecord[];
  count: number;
}

export interface DocumentSearchResult {
  id: string;
  text: string;
  similarity: number;
  documentId?: string;
  documentTitle?: string;
  documentProvenance?: DocumentProvenance;
  position?: number;
}

export interface DocumentSearchResponse {
  query: string;
  threshold: number;
  results: DocumentSearchResult[];
  count: number;
}

export interface DocumentUploadResult {
  ok: boolean;
  documentId: string;
  fragmentCount: number;
  filename?: string;
  contentType?: string;
  isYouTubeTranscript?: boolean;
  warnings?: string[];
}

export interface DocumentUpdateResult {
  ok: boolean;
  documentId: string;
  fragmentCount: number;
}

export interface DocumentBulkUploadItemResult {
  index: number;
  ok: boolean;
  filename: string;
  documentId?: string;
  fragmentCount?: number;
  error?: string;
  warnings?: string[];
}

export interface DocumentBulkUploadResult {
  ok: boolean;
  total: number;
  successCount: number;
  failureCount: number;
  results: DocumentBulkUploadItemResult[];
}

// Memory / context command types
export interface MemorySearchResult {
  id: string;
  text: string;
  createdAt: number;
  score: number;
}

export interface MemorySearchResponse {
  query: string;
  results: MemorySearchResult[];
  count: number;
  limit: number;
}

export interface MemoryRememberResponse {
  ok: boolean;
  id: string;
  text: string;
  createdAt: number;
}

export interface QuickContextResponse {
  query: string;
  answer: string;
  memories: MemorySearchResult[];
  documents: DocumentSearchResult[];
}

// Memory Viewer types
export interface MemoryBrowseItem {
  id: string;
  type: string;
  text: string;
  entityId: string | null;
  roomId: string | null;
  agentId: string | null;
  createdAt: number;
  metadata: Record<string, unknown> | null;
  source: string | null;
}

export interface MemoryBrowseQuery {
  type?: string;
  entityId?: string;
  /** Comma-joinable entity IDs for multi-identity people. */
  entityIds?: string[];
  roomId?: string;
  q?: string;
  limit?: number;
  offset?: number;
}

export interface MemoryBrowseResponse {
  memories: MemoryBrowseItem[];
  total: number;
  limit: number;
  offset: number;
}

export interface MemoryFeedQuery {
  type?: string;
  limit?: number;
  before?: number;
}

export interface MemoryFeedResponse {
  memories: MemoryBrowseItem[];
  count: number;
  limit: number;
  hasMore: boolean;
}

export interface MemoryStatsResponse {
  total: number;
  byType: Record<string, number>;
}

// MCP
export interface McpServerConfig {
  type: "stdio" | "streamable-http" | "sse";
  command?: string;
  args?: string[];
  url?: string;
  env?: Record<string, string>;
  headers?: Record<string, string>;
}

export interface McpMarketplaceResult {
  name: string;
  description?: string;
  connectionType: string;
  npmPackage?: string;
  dockerImage?: string;
}

export interface McpRegistryServerDetail {
  packages?: Array<{
    environmentVariables: Array<{
      name: string;
      default?: string;
      isRequired?: boolean;
    }>;
    packageArguments?: Array<{ default?: string }>;
  }>;
  remotes?: Array<{
    type?: string;
    url: string;
    headers: Array<{ name: string; isRequired?: boolean }>;
  }>;
}

export interface McpServerStatus {
  name: string;
  connected: boolean;
  error?: string;
}

// Share Ingest
export interface ShareIngestPayload {
  title?: string;
  url?: string;
  text?: string;
  files?: Array<{ name: string }>;
}

export interface ShareIngestItem {
  suggestedPrompt: string;
  files: Array<{ name: string }>;
}

// ── Workflow types ────────────────────────────────────────────────────────────

export type WorkflowMode = "local" | "cloud" | "disabled";
export type WorkflowRuntimeStatus = "ready" | "error";

export interface WorkflowStatusResponse {
  mode: WorkflowMode;
  host: string | null;
  status: WorkflowRuntimeStatus;
  cloudConnected: boolean;
  localEnabled: boolean;
  platform?: "desktop";
  cloudHealth?: "ok" | "degraded" | "unknown";
}

export interface WorkflowDefinitionNode {
  id: string;
  name: string;
  type: string;
  typeVersion?: number;
  /** Canvas position — [x, y]. Present on single-workflow GET; absent on list. */
  position?: [number, number];
  /** Node parameters. Present on single-workflow GET; absent on list. */
  parameters?: Record<string, unknown>;
  credentials?: Record<string, { id: string; name: string }>;
  disabled?: boolean;
  notes?: string;
  notesInFlow?: boolean;
  color?: string;
  continueOnFail?: boolean;
  executeOnce?: boolean;
  alwaysOutputData?: boolean;
  retryOnFail?: boolean;
  maxTries?: number;
  waitBetweenTries?: number;
  onError?: "continueErrorOutput" | "continueRegularOutput" | "stopWorkflow";
}

/** A single outbound connection edge from the workflow connection map. */
export interface WorkflowConnection {
  node: string;
  type: "main";
  index: number;
}

/**
 * Workflow connection map shape.
 * Keys are source node names; values group edges by output type.
 * Present on single-workflow GET only — list endpoint stays shallow.
 */
export type WorkflowConnectionMap = Record<
  string,
  { main?: WorkflowConnection[][] }
>;

export interface WorkflowDefinition {
  id: string;
  name: string;
  active: boolean;
  versionId?: string;
  description?: string;
  nodeCount?: number;
  nodes?: WorkflowDefinitionNode[];
  lastExecutionAt?: string;
  /** Connection graph. Present on single-workflow GET; absent on list. */
  connections?: WorkflowConnectionMap;
}

export type WorkflowRevisionOperation =
  | "update"
  | "activate"
  | "deactivate"
  | "tags"
  | "restore"
  | "delete";

export interface WorkflowRevision {
  id: string;
  workflowId: string;
  versionId: string;
  name: string;
  active: boolean;
  workflow?: WorkflowDefinition;
  createdAt: string;
  updatedAt: string;
  capturedAt: string;
  operation: WorkflowRevisionOperation;
}

export interface WorkflowExecutionEngineMetrics {
  provider: "smithers";
  nodes: number;
  levels: number;
  maxConcurrency: number;
  started: number;
  finished: number;
  failed: number;
  skipped: number;
  retries: number;
}

export interface WorkflowExecution {
  id: string;
  status:
    | "success"
    | "error"
    | "running"
    | "waiting"
    | "canceled"
    | "crashed"
    | "new"
    | "unknown";
  startedAt: string;
  stoppedAt?: string | null;
  mode?: string;
  workflowId?: string;
  data?: {
    resultData?: {
      runData?: Record<string, unknown[]>;
      error?: { message?: string; stack?: string };
      lastNodeExecuted?: string;
      engine?: WorkflowExecutionEngineMetrics;
    };
  };
}

export interface WorkflowEvaluationSampleNode {
  name: string;
  status: "success" | "error" | "unknown";
  itemCount: number;
  executionTimeMs?: number;
  error?: string;
  preview?: string;
}

export interface WorkflowEvaluationSample {
  id: string;
  workflowId: string;
  workflowName: string;
  workflowVersionId?: string;
  executionId: string;
  createdAt: string;
  input: {
    mode: string;
    triggerData?: Record<string, unknown>;
  };
  expected: {
    status: WorkflowExecution["status"];
    passed: boolean;
    lastNodeExecuted?: string;
    engine?: WorkflowExecutionEngineMetrics;
    error?: string;
    nodes: WorkflowEvaluationSampleNode[];
  };
  score: {
    pass: boolean;
    value: number;
    reason: string;
  };
  tags: string[];
}

export interface WorkflowEvaluationSuite {
  workflowId: string;
  workflowName: string;
  workflowVersionId?: string;
  generatedAt: string;
  sampleCount: number;
  samples: WorkflowEvaluationSample[];
  jsonl: string;
  optimizer: {
    engine: "smithers-gepa";
    target: "workflow-generation";
    suiteName: string;
    caseFile: string;
    recommendedCommand: string;
    recommendedEvalCommand: string;
    recommendedOptimizeCommand: string;
    recommendedObservabilityCommand: string;
    recommendedMetricsCommand: string;
    notes: string[];
  };
}

/**
 * One missing credential entry on a workflow generate response. `authUrl` is
 * a `eliza://settings/connectors/<provider>` deep-link the UI may surface.
 */
export interface WorkflowDefinitionMissingCredential {
  credType: string;
  authUrl?: string;
}

/**
 * Returned by `POST /api/workflow/workflows/generate` when the deployed workflow
 * references credentials the user hasn't connected yet. Carries the deployed
 * workflow's identity plus the list of unmet credential requirements so the
 * UI can render a CTA banner.
 */
export interface WorkflowDefinitionMissingCredentialsResponse {
  id: string;
  name: string;
  active: boolean;
  missingCredentials: WorkflowDefinitionMissingCredential[];
  warning: "missing credentials";
}

/**
 * Structured clarification request emitted by the plugin's workflow generator
 * when a node parameter cannot be resolved from the runtime context. The host
 * surfaces these as quick-pick buttons; on click the host calls
 * `/api/workflow/workflows/resolve-clarification` with the chosen value, which
 * patches the draft at `paramPath` and deploys — no LLM regeneration.
 *
 * Mirrors the plugin's `ClarificationRequest` (see
 * @elizaos/plugin-workflow `src/types/index.ts`). Re-declared here to
 * avoid a host → plugin import cycle.
 */
export interface WorkflowClarificationRequest {
  kind:
    | "target_channel"
    | "target_server"
    | "recipient"
    | "value"
    | "free_text";
  platform?: string;
  scope?: { guildId?: string };
  question: string;
  paramPath: string;
}

/** One server / workspace / contact-collection from a connector catalog. */
export interface WorkflowClarificationTargetGroup {
  platform: string;
  groupId: string;
  groupName: string;
  targets: Array<{
    id: string;
    name: string;
    kind: "channel" | "recipient" | "chat";
  }>;
}

/**
 * Returned by `POST /api/workflow/workflows/generate` when the LLM emitted one or
 * more `ClarificationRequest`s and the host needs the user to pick a target
 * before deploying. The `draft` is the unmodified workflow JSON from the
 * plugin (with the unresolved parameters left absent); `catalog` is a
 * snapshot of the relevant connector-target-catalog scoped to the
 * platforms referenced by the clarifications.
 */
export interface WorkflowDefinitionNeedsClarificationResponse {
  status: "needs_clarification";
  draft: Record<string, unknown>;
  clarifications: WorkflowClarificationRequest[];
  catalog: WorkflowClarificationTargetGroup[];
}

/** Resolution payload sent to /api/workflow/workflows/resolve-clarification. */
export interface WorkflowClarificationResolution {
  paramPath: string;
  value: string;
}

export interface WorkflowDefinitionResolveClarificationRequest {
  draft: Record<string, unknown>;
  resolutions: WorkflowClarificationResolution[];
  name?: string;
  workflowId?: string;
}

export type WorkflowDefinitionGenerateResponse =
  | WorkflowDefinition
  | WorkflowDefinitionMissingCredentialsResponse
  | WorkflowDefinitionNeedsClarificationResponse;

export function isMissingCredentialsResponse(
  res: WorkflowDefinitionGenerateResponse,
): res is WorkflowDefinitionMissingCredentialsResponse {
  const candidate = res as WorkflowDefinitionMissingCredentialsResponse;
  return (
    candidate.warning === "missing credentials" &&
    Array.isArray(candidate.missingCredentials)
  );
}

export function isNeedsClarificationResponse(
  res: WorkflowDefinitionGenerateResponse,
): res is WorkflowDefinitionNeedsClarificationResponse {
  const candidate = res as WorkflowDefinitionNeedsClarificationResponse;
  return (
    candidate.status === "needs_clarification" &&
    Array.isArray(candidate.clarifications) &&
    Array.isArray(candidate.catalog) &&
    typeof candidate.draft === "object" &&
    candidate.draft !== null
  );
}

export interface WorkflowDefinitionWriteNode {
  id?: string;
  name: string;
  type: string;
  typeVersion: number;
  position: [number, number];
  parameters: Record<string, unknown>;
  credentials?: Record<string, { id: string; name: string }>;
  disabled?: boolean;
  notes?: string;
  notesInFlow?: boolean;
  color?: string;
  continueOnFail?: boolean;
  executeOnce?: boolean;
  alwaysOutputData?: boolean;
  retryOnFail?: boolean;
  maxTries?: number;
  waitBetweenTries?: number;
  onError?: "continueErrorOutput" | "continueRegularOutput" | "stopWorkflow";
}

export interface WorkflowDefinitionWriteRequest {
  name: string;
  nodes: WorkflowDefinitionWriteNode[];
  connections: WorkflowConnectionMap;
  settings?: Record<string, unknown>;
}

export interface WorkflowDefinitionGenerateRequest {
  prompt: string;
  name?: string;
  workflowId?: string;
  /**
   * Optional originating conversation id. When present, the server reads
   * the conversation's tail inbound message metadata and threads platform
   * routing (Discord channelId/guildId, Telegram chatId, etc.) into the
   * workflow generator so the LLM can target "this channel" / "back to
   * here" without the user naming an ID.
   */
  bridgeConversationId?: string;
}
