/**
 * Read and write `.elizaos/template.json`, the managed-file ledger generated by
 * create and consumed by upgrade.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { ProjectTemplateMetadata } from "./types.js";

const METADATA_DIR = ".elizaos";
const METADATA_FILE = "template.json";

/**
 * Thrown when `.elizaos/template.json` exists but is unreadable, unparseable,
 * or structurally invalid. This is a J1 command boundary: `upgrade` must fail
 * closed with a clear error rather than proceed on corrupt/fabricated metadata.
 */
export class ProjectMetadataError extends Error {
  readonly metadataPath: string;

  constructor(metadataPath: string, detail: string, options?: { cause?: unknown }) {
    super(
      `Corrupt project metadata at ${metadataPath}: ${detail}. ` +
        "Fix or remove the file and re-run, or re-create the project.",
      options,
    );
    this.name = "ProjectMetadataError";
    this.metadataPath = metadataPath;
  }
}

function getMetadataPath(projectRoot: string): string {
  return path.join(projectRoot, METADATA_DIR, METADATA_FILE);
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function isStringRecord(value: unknown): value is Record<string, string> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return false;
  }
  return Object.values(value as Record<string, unknown>).every(
    (entry) => typeof entry === "string",
  );
}

/**
 * Validate the parsed JSON against the required shape of
 * `ProjectTemplateMetadata`. Only the fields `upgrade` actually depends on are
 * enforced as hard requirements; a file that parses to the wrong shape (e.g.
 * `{}`, an array, or a bare string) must be rejected so the caller never runs
 * on fabricated defaults. Returns a human-readable reason string when invalid.
 */
function validateMetadataShape(value: unknown): string | null {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return "expected a JSON object";
  }
  const record = value as Record<string, unknown>;
  if (!isNonEmptyString(record.templateId)) {
    return "missing or invalid 'templateId'";
  }
  if (!isStringRecord(record.values)) {
    return "missing or invalid 'values' (expected a string map)";
  }
  if (!isStringRecord(record.managedFiles)) {
    return "missing or invalid 'managedFiles' (expected a path->hash map)";
  }
  return null;
}

/**
 * Read the managed-file ledger for a generated project.
 *
 * Returns `null` only when the file is genuinely absent (a project that was
 * never scaffolded from a template has no upgrade state, a valid non-error
 * "no-data" outcome). If the file exists but cannot be read, parsed, or fails
 * shape validation, this throws {@link ProjectMetadataError} so `upgrade` stops
 * at the corrupt input instead of fabricating an empty/default metadata object.
 */
export function readProjectMetadata(
  projectRoot: string,
): ProjectTemplateMetadata | null {
  const metadataPath = getMetadataPath(projectRoot);
  if (!fs.existsSync(metadataPath)) {
    return null;
  }

  let raw: string;
  try {
    raw = fs.readFileSync(metadataPath, "utf-8");
  } catch (error) {
    throw new ProjectMetadataError(metadataPath, "file could not be read", {
      cause: error,
    });
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    const detail =
      error instanceof Error ? `invalid JSON (${error.message})` : "invalid JSON";
    throw new ProjectMetadataError(metadataPath, detail, { cause: error });
  }

  const shapeError = validateMetadataShape(parsed);
  if (shapeError) {
    throw new ProjectMetadataError(metadataPath, shapeError);
  }

  return parsed as ProjectTemplateMetadata;
}

export function writeProjectMetadata(
  projectRoot: string,
  metadata: ProjectTemplateMetadata,
): void {
  const metadataPath = getMetadataPath(projectRoot);
  fs.mkdirSync(path.dirname(metadataPath), { recursive: true });
  fs.writeFileSync(metadataPath, `${JSON.stringify(metadata, null, 2)}\n`);
}
