export const REPLY_ACTION_NAME = "REPLY";
export const NONE_ACTION_NAME = "NONE";
export const IGNORE_ACTION_NAME = "IGNORE";

export const NON_EXECUTABLE_RESPONSE_ACTION_NAMES = [
	REPLY_ACTION_NAME,
	NONE_ACTION_NAME,
	IGNORE_ACTION_NAME,
] as const;
