window.SCENARIO_RUN_DATA = {
  schema: "eliza_scenario_run_viewer_v1",
  generatedAt: "2026-06-30T04:50:37.843Z",
  runDir:
    "/Users/shawwalters/eliza-workspace/eliza/eliza/.claude/worktrees/agent-a1e006784a3648282/.github/issue-evidence/8934-voice-audio-capture",
  matrixPath:
    "/Users/shawwalters/eliza-workspace/eliza/eliza/.claude/worktrees/agent-a1e006784a3648282/.github/issue-evidence/8934-voice-audio-capture/matrix.json",
  nativeJsonlPath: null,
  nativeManifestPath: null,
  report: {
    runId: "issue-8934-evidence",
    startedAtIso: "2026-06-30T04:50:37.618Z",
    completedAtIso: "2026-06-30T04:50:37.817Z",
    providerName: "deterministic-llm-proxy",
    scenarios: [
      {
        id: "voice-workbench-room",
        title: "Voice Workbench: multi-speaker room over a voice turn",
        domain: "voice",
        tags: ["deterministic", "voice"],
        status: "passed",
        durationMs: 0,
        turns: [
          {
            name: "multi-speaker voice scenario",
            kind: "voice",
            responseText: "voice:voice-room-demo pass (ran, 9 cases)",
            actionsCalled: [],
            durationMs: 0,
            failedAssertions: [],
            audioArtifacts: [
              {
                turnIndex: 0,
                kind: "generated",
                path: "audio/voice-room-demo/corpus.wav",
                sampleRate: 16000,
                durationMs: 8008,
              },
              {
                turnIndex: 0,
                kind: "consumed",
                path: "audio/voice-room-demo/turn-0.wav",
                sampleRate: 16000,
                durationMs: 2854,
                speakerLabel: "alice",
              },
              {
                turnIndex: 1,
                kind: "consumed",
                path: "audio/voice-room-demo/turn-1.wav",
                sampleRate: 16000,
                durationMs: 3008,
                speakerLabel: "bob",
              },
              {
                turnIndex: 2,
                kind: "consumed",
                path: "audio/voice-room-demo/turn-2.wav",
                sampleRate: 16000,
                durationMs: 2146,
                speakerLabel: "alice",
              },
            ],
          },
        ],
        finalChecks: [],
        actionsCalled: [],
        failedAssertions: [],
        providerName: "deterministic-llm-proxy",
      },
    ],
    totals: { passed: 1, failed: 0, skipped: 0, flakyPassed: 0, costUsd: 0 },
    totalCount: 1,
    passedCount: 1,
    failedCount: 0,
    skippedCount: 0,
    flakyPassedCount: 0,
    totalCostUsd: 0,
  },
  trajectories: {
    root: "/Users/shawwalters/eliza-workspace/eliza/eliza/.claude/worktrees/agent-a1e006784a3648282/.github/issue-evidence/8934-voice-audio-capture/trajectories",
    files: [],
    summaries: [],
  },
  nativeExport: { manifest: null, rows: [] },
};
