/** Public surface of @elizaos/evidence: schema, bundle builder, provenance, ingestors. */

// Tiered heuristic analyzer registry (#14542): OCR engines, colour/brand/diff
// heuristics, perceptual hash, aria-tree ops, video keyframes, and the runner
// that fans them over a bundle into per-subject `analysis.json`.
export {
  ANALYZERS,
  type AnalysisDocument,
  type AnalyzeOptions,
  type AnalyzeResult,
  type Analyzer,
  type AnalyzerContext,
  type AnalyzerExpectations,
  type AnalyzerFragment,
  type AnalyzerInput,
  type AnalyzerResult,
  type AnalyzerStatus,
  AppleVisionOcrEngine,
  type AriaDiffEntry,
  type AriaNode,
  type AriaTreeData,
  analyzeArtifacts,
  analyzersForKind,
  analyzersForTier,
  ariaTreeAnalyzer,
  type BaselineResolver,
  BRAND_THRESHOLDS,
  type BrandCheck,
  type BrandData,
  brandColorFractions,
  brandRulesAnalyzer,
  type ChangeData,
  type ChangedRegion,
  CORNER_POSITIONS,
  type ColorBucket,
  type ColorFractions,
  type CornerPosition,
  type CornerSwatch,
  type CornersData,
  changeMetric,
  classifyColor,
  clusterRegions,
  colorCornersAnalyzer,
  colorFractionsFromRaw,
  colorPaletteAnalyzer,
  cornerSwatches,
  diffAriaSnapshots,
  diffChangeAnalyzer,
  diffRegionAnalyzer,
  dominantPalette,
  type EmitArtifact,
  evaluateBrand,
  evaluateRegionExpectations,
  extractKeyframes,
  ffmpegAvailable,
  getAnalyzer,
  hammingDistance,
  isSameScreen,
  type KeyframeRecord,
  type KeyframesData,
  makeOcrAnalyzer,
  normalizeAriaSnapshot,
  type OcrAvailable,
  type OcrData,
  type OcrEngine,
  type OcrRecognition,
  type OcrUnavailable,
  ocrTesseractAnalyzer,
  ocrUnlimitedAnalyzer,
  type PaletteData,
  type PaletteSwatch,
  type PerceptualHashData,
  type PruneOptions,
  parseAriaSnapshot,
  perceptualHash,
  perceptualHashAnalyzer,
  pruneAriaSnapshot,
  type RegionAssertion,
  type RegionDiffData,
  type RegionExpectation,
  round4,
  SAME_SCREEN_THRESHOLD,
  type SubjectAnalysis,
  TesseractOcrEngine,
  tierRunnable,
  UnlimitedOcrEngine,
  videoKeyframesAnalyzer,
} from "./analyzers/index.ts";
export {
  type AddArtifactOptions,
  type BundleProvenance,
  type CreateBundleOptions,
  createBundle,
  EvidenceBundle,
  type FinalizeResult,
  formatRunId,
  type VerifyIssue,
  type VerifyReport,
  verifyBundle,
} from "./bundle.ts";
export { canonicalJson, canonicalJsonBytes } from "./canonical.ts";
export {
  EvidenceError,
  type EvidenceErrorOptions,
  EvidenceValidationError,
  type ValidationIssue,
} from "./errors.ts";
export {
  type IngestResult,
  ingestAllSilos,
  ingestNamedSilo,
  SILO_NAMES,
} from "./ingest.ts";
export {
  buildEnvFingerprint,
  collectGitProvenance,
  type GitProvenance,
  type ProcessFacts,
  resolveRunnerKind,
} from "./provenance.ts";
export {
  ARTIFACT_KINDS,
  type ArtifactEntry,
  type ArtifactKind,
  type BundleManifest,
  type BundleMeta,
  isBundleRelativePath,
  parseManifest,
  parseMeta,
  RUNNER_KINDS,
  type RunnerKind,
  TIERS,
  type Tier,
} from "./schema.ts";
