/** Public surface of @elizaos/evidence: schema, bundle builder, provenance, ingestors. */

// Tiered heuristic analyzer registry (#14542): OCR engines, colour/brand/diff
// heuristics, perceptual hash, aria-tree ops, video keyframes, and the runner
// that fans them over a bundle into per-subject `analysis.json`.
export {
  ANALYZERS,
  type AnalysisDocument,
  type AnalyzeOptions,
  type AnalyzeResult,
  type Analyzer,
  type AnalyzerContext,
  type AnalyzerExecutor,
  type AnalyzerExpectations,
  type AnalyzerFragment,
  type AnalyzerInput,
  type AnalyzerResult,
  type AnalyzerStatus,
  AppleVisionOcrEngine,
  type AriaDiffEntry,
  type AriaNode,
  type AriaTreeData,
  analyzeArtifacts,
  analyzersForKind,
  analyzersForTier,
  ariaTreeAnalyzer,
  type BaselineResolver,
  BRAND_THRESHOLDS,
  type BrandCheck,
  type BrandData,
  brandColorFractions,
  brandRulesAnalyzer,
  type ChangeData,
  type ChangedRegion,
  CORNER_POSITIONS,
  type ColorBucket,
  type ColorFractions,
  type CornerPosition,
  type CornerSwatch,
  type CornersData,
  changeMetric,
  classifyColor,
  clusterRegions,
  colorCornersAnalyzer,
  colorFractionsFromRaw,
  colorPaletteAnalyzer,
  cornerSwatches,
  defaultServeStatePath,
  diffAriaSnapshots,
  diffChangeAnalyzer,
  diffRegionAnalyzer,
  dominantPalette,
  type EmitArtifact,
  evaluateBrand,
  evaluateRegionExpectations,
  extractKeyframes,
  ffmpegAvailable,
  getAnalyzer,
  hammingDistance,
  INLINE_EXECUTOR,
  InlineExecutor,
  isSameScreen,
  type KeyframeRecord,
  type KeyframesData,
  makeOcrAnalyzer,
  normalizeAriaSnapshot,
  type OcrAvailable,
  type OcrData,
  type OcrEngine,
  type OcrGroundedRegion,
  type OcrRecognition,
  type OcrUnavailable,
  ocrTesseractAnalyzer,
  ocrUnlimitedAnalyzer,
  type PaletteData,
  type PaletteSwatch,
  type PerceptualHashData,
  type PruneOptions,
  parseAriaSnapshot,
  parseGroundingDecorations,
  perceptualHash,
  perceptualHashAnalyzer,
  pruneAriaSnapshot,
  type RegionAssertion,
  type RegionDiffData,
  type RegionExpectation,
  round4,
  runAnalyzerInline,
  SAME_SCREEN_THRESHOLD,
  type SubjectAnalysis,
  slugForVideo,
  TesseractOcrEngine,
  tierRunnable,
  UNLIMITED_OCR_PROMPT,
  UnlimitedOcrEngine,
  videoKeyframesAnalyzer,
} from "./analyzers/index.ts";
export {
  type AddArtifactOptions,
  type BundleProvenance,
  type CreateBundleOptions,
  createBundle,
  EvidenceBundle,
  type FinalizeResult,
  formatRunId,
  type VerifyIssue,
  type VerifyReport,
  verifyBundle,
} from "./bundle.ts";
export { canonicalJson, canonicalJsonBytes } from "./canonical.ts";
export {
  fingerprintPublicKey,
  type GeneratedKeypair,
  generateCertificationKeypair,
  type ResolveSigningKeyOptions,
  resolveSigningKey,
  SIGNING_KEY_ENV_VAR,
} from "./certify/keys.ts";
// One-command certify orchestrator (#14546): chains matrix → ingest →
// analyze → vision-qa → rollup → reviewer merge → sign → self-verify.
export {
  type CertifyOptions,
  type CertifyResult,
  type MatrixLaneResult,
  type MatrixRunner,
  type MatrixRunResult,
  mergeReviewerVerdicts,
  orchestrateCertify,
  parseReviewerVerdicts,
  type ReviewerOverride,
  type ReviewerVerdictsDocument,
  type StepOutcome,
  spawnRunAllTests,
} from "./certify/orchestrate.ts";
export {
  type AnalysisFinding,
  type ArtifactRequirement,
  type CertificationRequirements,
  type LaneRequirement,
  type LaneRollup,
  parseRequirements,
  parseVerdictsDocument,
  type RollupResult,
  type RollupSummary,
  rollupBundle,
} from "./certify/rollup.ts";
export {
  type Certification,
  type CertificationPayload,
  type CertificationReviewer,
  type CertificationSignature,
  type CertificationVerdict,
  parseCertification,
  parseCertificationPayload,
  REVIEWER_KINDS,
  type ReviewerKind,
  tierSatisfies,
  VERDICT_VALUES,
  type VerdictValue,
} from "./certify/schema.ts";
export {
  CERTIFICATION_FAILURE_CODES,
  type CertificationFailure,
  type CertificationFailureCode,
  type CertificationVerifyOptions,
  type CertificationVerifyReport,
  signCertification,
  verifyCertification,
} from "./certify/sign.ts";
export {
  EvidenceError,
  type EvidenceErrorOptions,
  EvidenceValidationError,
  type ValidationIssue,
} from "./errors.ts";
export {
  type IngestResult,
  ingestAllSilos,
  ingestNamedSilo,
  SILO_NAMES,
} from "./ingest.ts";
export {
  buildEnvFingerprint,
  collectGitProvenance,
  type GitProvenance,
  type ProcessFacts,
  resolveRunnerKind,
} from "./provenance.ts";
// GPU vision job queue (#14543): capture lanes enqueue images as they land, a
// resident GPU worker runs gpu-tier analyzers against the vision service and
// streams results into analysis.json; QueueExecutor routes the runner's gpu work
// through it. Drains to honest `skipped` records when no service is reachable.
export {
  type ClaimedJob,
  claimOrder,
  createWorkerState,
  DEFAULT_LIMITS as QUEUE_DEFAULT_LIMITS,
  decideEnqueue,
  drainSkipResult,
  type EnqueueParams,
  FileJobQueue,
  type FileJobQueueOptions,
  isConnectivityFailure,
  type JobOutcomeStatus,
  type JobResult,
  makeJobId,
  mergeAnalyzerResult,
  onServiceOk,
  onServiceUnreachable,
  type ProcessOutcome,
  parseJob,
  processJob,
  QUEUE_DIRS,
  QueueBackpressureError,
  QueueExecutor,
  type QueueExecutorOptions,
  type QueueJob,
  QueueJobInvalidError,
  type QueueLimits,
  type RunWorkerOptions,
  runQueueCli,
  runQueueWorker,
  shouldDrain,
  type WorkerAction,
  type WorkerEvent,
  type WorkerState,
} from "./queue/index.ts";
export {
  ARTIFACT_KINDS,
  type ArtifactEntry,
  type ArtifactKind,
  type BundleManifest,
  type BundleMeta,
  isBundleRelativePath,
  parseManifest,
  parseMeta,
  RUNNER_KINDS,
  type RunnerKind,
  TIERS,
  type Tier,
} from "./schema.ts";
// Video evidence lanes (#14545): MP4 normalization, video ingest with keyframe
// analysis, the data-driven walkthrough driver, and walkthrough definition
// loading/orchestration over the shipped dashboard fixture.
export {
  type RunWalkthroughOptions,
  runWalkthrough,
  type StepLog,
  type WalkthroughRunResult,
} from "./video/driver.ts";
export { type FixtureServer, serveFixture } from "./video/fixture-server.ts";
export {
  type IngestVideoOptions,
  type IngestVideoResult,
  ingestVideo,
  VIDEO_GRANULARITIES,
  type VideoGranularity,
} from "./video/ingest.ts";
export {
  type NormalizeOutcome,
  normalizeVideo,
  probeVideo,
  type VideoProbe,
  videoToolsAvailable,
} from "./video/normalize.ts";
export {
  parseWalkthroughDef,
  WALKTHROUGH_ACTIONS,
  type WalkthroughAction,
  type WalkthroughDef,
  type WalkthroughStep,
} from "./video/walkthrough-schema.ts";
export {
  FIXTURE_DIR,
  loadAllWalkthroughDefs,
  loadWalkthroughDef,
  type RunAndIngestOptions,
  type RunAndIngestResult,
  runAndIngestWalkthrough,
  WALKTHROUGHS_DIR,
} from "./video/walkthroughs.ts";
// Vision-QA VLM screenshot Q&A layer (#14544).
export {
  ANTHROPIC_BASE_URL,
  type AnalysisInput,
  AnthropicBackend,
  type AskOptions,
  type AskResult,
  askAboutImage,
  askBatch,
  type BatchEntry,
  type BatchResult,
  buildQaRecord,
  cacheFilePath,
  createBackendClient,
  DEFAULT_ANTHROPIC_MODEL,
  DEFAULT_MAX_EDGE,
  type ImageDimensions,
  OpenAiCompatibleBackend,
  type PreparedImage,
  parseAnswers,
  prepareImage,
  type QaRecord,
  queryHash,
  readCache,
  renderQuestionPrompt,
  resolveBackend,
  runVisionQaCli,
  type SuggestContext,
  SYSTEM_RUBRIC,
  scaleToMaxEdge,
  suggestQuestions,
  type TokenUsage,
  VISION_QA_ENV,
  type VisionAnswer,
  type VisionBackend,
  type VisionBackendClient,
  type VisionProvenance,
  type VisionQaCliIo,
  type VisionQuestion,
  writeCache,
  writeQaRecord,
} from "./vision-qa/index.ts";
