/**
 * Scenario-trajectory → `eliza_native_v1` corpus bridge.
 *
 * `eliza-scenarios run <dir> --run-dir <runDir>` makes the runtime's
 * `JsonFileTrajectoryRecorder` write one `RecordedTrajectory` JSON file per
 * agent turn under `<runDir>/trajectories/<agentId>/<trajectoryId>.json`. That
 * shape (`stages[].model`) is a per-stage trace, not the canonical training
 * corpus record. The eliza-1 training prep script
 * (`packages/training/scripts/prepare_eliza1_trajectory_dataset.py`) ingests
 * `eliza_native_v1` model-boundary rows — one row per Vercel AI SDK
 * `generateText`/`streamText` call. This module converts the recorded stages
 * into those rows so the scenario corpus can feed model training.
 *
 * Output shape mirrors `packages/core/src/services/trajectory-types.ts`
 * (`ElizaNativeTrajectoryRow`) and the contract in
 * `packages/training/docs/dataset/CANONICAL_RECORD.md`. The exporter redacts
 * obvious secrets/contact data/coordinates before writing JSONL and emits a
 * privacy attestation sidecar that the training path can verify.
 */

import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import type {
  RecordedModelCall,
  RecordedStage,
  RecordedTrajectory,
} from "@elizaos/core";
import { logger } from "@elizaos/logger";
import { toRecord } from "./utils.js";

const NATIVE_FORMAT = "eliza_native_v1" as const;
const NATIVE_SCHEMA_VERSION = 1 as const;
const GENERATE_TEXT_BOUNDARY = "vercel_ai_sdk.generateText" as const;
export const SCENARIO_NATIVE_EXPORT_SCHEMA =
  "eliza_scenario_native_export" as const;
export const SCENARIO_NATIVE_EXPORT_VERSION = 1 as const;
export const SCENARIO_NATIVE_PRIVACY_ATTESTATION_SCHEMA =
  "eliza.privacy_filter_attestation.v1" as const;
export const SCENARIO_NATIVE_PRIVACY_ATTESTATION_VERSION = 1 as const;

/**
 * Per-scenario assertion outcome, keyed by scenario id. Threaded into the
 * exporter so failed/regressed trajectories are not emitted as gold-weight
 * training rows. The recorder's own `trajectory.status` is the mechanical
 * lifecycle (finished/errored) and does NOT reflect assertion pass/fail — only
 * the scenario report carries that.
 */
export type ScenarioOutcome = "passed" | "failed" | "skipped";
export type ScenarioOutcomeMap = ReadonlyMap<string, ScenarioOutcome>;
/**
 * Per-scenario numeric judge score (`ScenarioReport.judgeScore`, the minimum
 * across all judged turns + judgeRubric final checks), keyed by scenario id.
 * Threaded into the exporter so training prep can reward-weight rows
 * (#8795) instead of only routing on pass/fail.
 */
export type ScenarioJudgeScoreMap = ReadonlyMap<string, number>;
export type ScenarioTierMap = ReadonlyMap<string, string>;

export interface NativeBoundaryRow {
  format: typeof NATIVE_FORMAT;
  schemaVersion: typeof NATIVE_SCHEMA_VERSION;
  boundary: typeof GENERATE_TEXT_BOUNDARY;
  privacyAttestation?: NativeRowPrivacyAttestation;
  /**
   * Scenario assertion outcome consumed by the training prep scorer
   * (`native_success_and_score` in prepare_eliza1_trajectory_dataset.py). Kept
   * separate from top-level `status`, which belongs to the canonical native
   * trajectory lifecycle contract.
   */
  scenarioStatus?: ScenarioOutcome;
  /**
   * Numeric LLM-judge score in [0, 1] for the source scenario (minimum across
   * its judged turns + judgeRubric final checks). Also mirrored as
   * `metadata.judge_score` so the training reward pipeline reads it without
   * knowing the row shape (#8795).
   */
  judgeScore?: number;
  /** Optional persona-scenario complexity tier (`T1`..`T4`) for corpus slicing. */
  tier?: string;
  request: {
    system?: string;
    messages?: unknown[];
    prompt?: string;
    tools?: unknown;
    toolChoice?: unknown;
    providerOptions?: unknown;
    settings?: {
      temperature?: number;
      maxOutputTokens?: number;
      topP?: number;
    };
  };
  response: {
    text: string;
    toolCalls?: Array<{
      toolCallId?: string;
      toolName: string;
      input: unknown;
    }>;
    finishReason?: string;
    usage?: {
      promptTokens?: number;
      completionTokens?: number;
      totalTokens?: number;
      cacheReadInputTokens?: number;
      cacheCreationInputTokens?: number;
    };
  };
  trajectoryId: string;
  agentId: string;
  scenarioId: string | null;
  batchId: string | null;
  stepId: string;
  callId: string;
  stepIndex: number;
  callIndex: number;
  timestamp: number;
  purpose?: string;
  stepType?: string;
  model?: string;
  modelVersion?: string;
  modelType?: string;
  provider?: string;
  metadata: Record<string, unknown>;
}

/**
 * Truthful source label for scenario-runner native exports. Scenario data is
 * SYNTHETIC (generated by the runner), NOT a reviewed real-user export —
 * before #13623 the attestation mislabeled it `"user_export"` / `realUserExport:
 * true`, which could wave synthetic, unreviewed data through a privacy gate as
 * if it were reviewed real-user data.
 */
export const SCENARIO_NATIVE_SOURCE_KIND = "scenario_synthetic" as const;

export interface NativeRowPrivacyAttestation {
  schema: typeof SCENARIO_NATIVE_PRIVACY_ATTESTATION_SCHEMA;
  version: typeof SCENARIO_NATIVE_PRIVACY_ATTESTATION_VERSION;
  source: "scenario_native_export";
  redacted: true;
  /**
   * Reflects the REAL privacy-gate result (no residual findings), not a
   * hardcoded `true`. A row carrying an unredacted residual stamps
   * `reviewed:false`/`passed:false` so it can't pass the gate (#13623).
   */
  reviewed: boolean;
  passed: boolean;
  attestationPath: string;
}

interface ScenarioNativePrivacyAttestation {
  schema: typeof SCENARIO_NATIVE_PRIVACY_ATTESTATION_SCHEMA;
  version: typeof SCENARIO_NATIVE_PRIVACY_ATTESTATION_VERSION;
  generated_at: string;
  passed: boolean;
  strict: true;
  sourceKind: typeof SCENARIO_NATIVE_SOURCE_KIND;
  source: {
    kind: typeof SCENARIO_NATIVE_SOURCE_KIND;
    realUserExport: false;
    inputPathRefs: string[];
  };
  privacy: {
    reviewed: boolean;
    realUserExport: false;
    attestationType: "privacy_filter";
  };
  input_count: number;
  output_count: number;
  redaction_count: number;
  categories: Record<PrivacyCategory, number>;
  residual_findings: {
    count: number;
    by_label: Record<string, number>;
  };
  residual_findings_count: number;
  input_path_refs: string[];
  artifacts: {
    redacted_jsonl: {
      path: string;
      path_ref: string;
      sha256: string;
      rows: number;
    };
  };
  gate: {
    passed: boolean;
    strict: true;
    sourceKind: typeof SCENARIO_NATIVE_SOURCE_KIND;
    input_count: number;
    output_count: number;
    redaction_count: number;
    categories: Record<PrivacyCategory, number>;
    residual_findings: {
      count: number;
      by_label: Record<string, number>;
    };
    residual_findings_count: number;
  };
}

export interface ScenarioNativeExportManifest {
  schema: typeof SCENARIO_NATIVE_EXPORT_SCHEMA;
  schemaVersion: typeof SCENARIO_NATIVE_EXPORT_VERSION;
  generatedAt: string;
  runDir: string;
  trajectoriesDir: string;
  jsonlPath: string;
  manifestPath: string;
  privacyAttestationPath: string;
  counts: {
    trajectoryFiles: number;
    parsedTrajectories: number;
    skippedFiles: number;
    rows: number;
    passedRows: number;
    failedRows: number;
    skippedScenarioRows: number;
    unknownOutcomeRows: number;
  };
  runIds: string[];
  scenarioIds: string[];
  agentIds: string[];
  privacy: {
    reviewed: boolean;
    attestationSchema: typeof SCENARIO_NATIVE_PRIVACY_ATTESTATION_SCHEMA;
    attestationVersion: typeof SCENARIO_NATIVE_PRIVACY_ATTESTATION_VERSION;
    attestationPath: string;
    redactions: number;
    residualFindings: number;
    categories: Record<PrivacyCategory, number>;
  };
}

type PrivacyCategory = "secret" | "geo" | "contact" | "backend";

interface PrivacyFilterPattern {
  category: PrivacyCategory;
  label: string;
  pattern: RegExp;
  replacement: string;
}

interface PrivacyFilterStats {
  redactionsTotal: number;
  redactionsByCategory: Record<PrivacyCategory, number>;
  redactionsByLabel: Record<string, number>;
  residualTotal: number;
  residualByLabel: Record<string, number>;
}

const LIFEOPS_NATIVE_TASKS = [
  "calendar_extract",
  "schedule_plan",
  "reminder_dispatch",
  "inbox_triage",
  "meeting_prep",
  "morning_brief",
  "health_checkin",
  "screentime_recap",
] as const;

const LIFEOPS_NATIVE_TASK_SET = new Set<string>(LIFEOPS_NATIVE_TASKS);

const ORCHESTRATOR_NATIVE_TASKS = ["goal_verification"] as const;

const ORCHESTRATOR_NATIVE_TASK_SET = new Set<string>(ORCHESTRATOR_NATIVE_TASKS);

const GEO_REPLACEMENT = "[REDACTED_GEO]" as const;
const PRIVACY_CATEGORIES: PrivacyCategory[] = [
  "secret",
  "geo",
  "contact",
  "backend",
];
const PRIVACY_PATTERNS: PrivacyFilterPattern[] = [
  {
    category: "secret",
    label: "openai-key",
    pattern: /\bsk-[A-Za-z0-9_-]{16,}\b/g,
    replacement: "<REDACTED:openai-key>",
  },
  {
    category: "secret",
    label: "anthropic-key",
    pattern: /\bsk-ant-[A-Za-z0-9_-]{16,}\b/g,
    replacement: "<REDACTED:anthropic-key>",
  },
  {
    category: "secret",
    label: "bearer",
    pattern: /\bBearer\s+[A-Za-z0-9._-]{16,}\b/g,
    replacement: "<REDACTED:bearer>",
  },
  {
    category: "secret",
    label: "github-token",
    pattern: /\bghp_[A-Za-z0-9]{20,}\b/g,
    replacement: "<REDACTED:github-token>",
  },
  {
    category: "secret",
    label: "aws-access-key",
    pattern: /\bAKIA[0-9A-Z]{16}\b/g,
    replacement: "<REDACTED:aws-access-key>",
  },
  {
    category: "geo",
    label: "coords-json-block",
    pattern:
      /"coords"\s*:\s*\{\s*"latitude"\s*:\s*-?\d+(?:\.\d+)?\s*,\s*"longitude"\s*:\s*-?\d+(?:\.\d+)?(?:\s*,\s*"[A-Za-z_][A-Za-z0-9_]*"\s*:\s*[^,}]+)*\s*\}/g,
    replacement: GEO_REPLACEMENT,
  },
  {
    category: "geo",
    label: "latitude-longitude-json-pair",
    pattern:
      /"latitude"\s*:\s*-?\d+(?:\.\d+)?\s*,\s*"longitude"\s*:\s*-?\d+(?:\.\d+)?/g,
    replacement: GEO_REPLACEMENT,
  },
  {
    category: "geo",
    label: "location-decimal-pair",
    pattern:
      /\b(?:current\s+location|location|coords|coordinates)\s*[:=]\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?/gi,
    replacement: GEO_REPLACEMENT,
  },
  {
    category: "geo",
    label: "labeled-lat-lng",
    pattern:
      /\b(?:lat|latitude)\s*[:=]\s*-?\d+(?:\.\d+)?\s*[,;]\s*(?:lng|lon|long|longitude)\s*[:=]\s*-?\d+(?:\.\d+)?/gi,
    replacement: GEO_REPLACEMENT,
  },
  {
    category: "geo",
    label: "bare-decimal-pair",
    pattern: /\b-?\d{1,3}\.\d{2,}\s*,\s*-?\d{1,3}\.\d{2,}\b/g,
    replacement: GEO_REPLACEMENT,
  },
  {
    category: "contact",
    label: "email",
    pattern: /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g,
    replacement: "<REDACTED:contact-email>",
  },
  {
    category: "contact",
    label: "phone",
    pattern:
      /(?:\+\d{1,3}[\s.-]?)?(?:\(\d{3}\)|\d{3})[\s.-]\d{3}[\s.-]\d{4}\b/g,
    replacement: "<REDACTED:contact-phone>",
  },
  {
    category: "contact",
    label: "handle",
    pattern: /(@[a-zA-Z0-9_.-]{2,})/g,
    replacement: "<REDACTED:contact-handle>",
  },
  {
    category: "contact",
    label: "known-pii-name",
    pattern: /\b(?:Jill|Marco|Sarah|Suran|Sam)\b/g,
    replacement: "<REDACTED:known-name>",
  },
];
const LATITUDE_KEYS = new Set(["lat", "latitude"]);
const LONGITUDE_KEYS = new Set(["lng", "lon", "long", "longitude"]);
const COORDINATE_CONTAINER_KEYS = new Set([
  "coords",
  "coordinates",
  "currentlocation",
  "geo",
  "geolocation",
  "location",
]);

function newPrivacyFilterStats(): PrivacyFilterStats {
  return {
    redactionsTotal: 0,
    redactionsByCategory: { secret: 0, geo: 0, contact: 0, backend: 0 },
    redactionsByLabel: {},
    residualTotal: 0,
    residualByLabel: {},
  };
}

function noteRedaction(
  stats: PrivacyFilterStats,
  category: PrivacyCategory,
  label: string,
): void {
  stats.redactionsTotal += 1;
  stats.redactionsByCategory[category] += 1;
  stats.redactionsByLabel[label] = (stats.redactionsByLabel[label] ?? 0) + 1;
}

function noteResidual(stats: PrivacyFilterStats, label: string): void {
  stats.residualTotal += 1;
  stats.residualByLabel[label] = (stats.residualByLabel[label] ?? 0) + 1;
}

function filterPrivacyText(text: string, stats: PrivacyFilterStats): string {
  let out = text;
  for (const spec of PRIVACY_PATTERNS) {
    out = out.replace(spec.pattern, () => {
      noteRedaction(stats, spec.category, spec.label);
      return spec.replacement;
    });
  }
  return out;
}

function normalizedStructuralKey(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function coordinateNumber(value: unknown, latitude: boolean): number | null {
  if (typeof value === "boolean") return null;
  const number =
    typeof value === "number"
      ? value
      : typeof value === "string" && /^-?\d+(?:\.\d+)?$/.test(value.trim())
        ? Number(value.trim())
        : Number.NaN;
  if (!Number.isFinite(number)) return null;
  if (latitude && (number < -90 || number > 90)) return null;
  if (!latitude && (number < -180 || number > 180)) return null;
  return number;
}

function hasCoordinatePair(value: unknown): boolean {
  return (
    Array.isArray(value) &&
    value.length >= 2 &&
    coordinateNumber(value[0], true) !== null &&
    coordinateNumber(value[1], false) !== null
  );
}

function structuredCoordinatePairs(
  record: Record<string, unknown>,
): Array<[string, string]> {
  const byNormalizedKey = new Map<string, string>();
  for (const key of Object.keys(record)) {
    byNormalizedKey.set(normalizedStructuralKey(key), key);
  }
  const pairs: Array<[string, string]> = [];
  for (const latKeyName of LATITUDE_KEYS) {
    const latKey = byNormalizedKey.get(latKeyName);
    if (!latKey || coordinateNumber(record[latKey], true) === null) continue;
    for (const lonKeyName of LONGITUDE_KEYS) {
      const lonKey = byNormalizedKey.get(lonKeyName);
      if (!lonKey || coordinateNumber(record[lonKey], false) === null) {
        continue;
      }
      pairs.push([latKey, lonKey]);
      break;
    }
  }
  return pairs;
}

function filterPrivacyValue(
  value: unknown,
  stats: PrivacyFilterStats,
  parentKey?: string,
): unknown {
  if (typeof value === "string") return filterPrivacyText(value, stats);
  if (Array.isArray(value)) {
    if (
      parentKey &&
      COORDINATE_CONTAINER_KEYS.has(normalizedStructuralKey(parentKey)) &&
      hasCoordinatePair(value)
    ) {
      noteRedaction(stats, "geo", "structured-coordinates");
      return value.map((item, index) =>
        index < 2 ? GEO_REPLACEMENT : filterPrivacyValue(item, stats),
      );
    }
    return value.map((item) => filterPrivacyValue(item, stats));
  }
  const record = toRecord(value);
  if (!record) return value;
  const out: Record<string, unknown> = {};
  const keyCounts = new Map<string, number>();
  for (const [rawKey, rawChild] of Object.entries(record)) {
    const filteredKey = filterPrivacyText(rawKey, stats);
    const count = keyCounts.get(filteredKey) ?? 0;
    keyCounts.set(filteredKey, count + 1);
    const key = count === 0 ? filteredKey : `${filteredKey}__${count}`;
    out[key] = filterPrivacyValue(rawChild, stats, key);
  }
  for (const [latKey, lonKey] of structuredCoordinatePairs(out)) {
    noteRedaction(stats, "geo", "structured-coordinates");
    out[latKey] = GEO_REPLACEMENT;
    out[lonKey] = GEO_REPLACEMENT;
  }
  return out;
}

function countPrivacyResiduals(
  value: unknown,
  stats: PrivacyFilterStats,
): void {
  if (typeof value === "string") {
    for (const spec of PRIVACY_PATTERNS) {
      const matches = value.match(spec.pattern);
      if (!matches) continue;
      for (const _match of matches) noteResidual(stats, spec.label);
    }
    return;
  }
  if (Array.isArray(value)) {
    for (const item of value) countPrivacyResiduals(item, stats);
    return;
  }
  const record = toRecord(value);
  if (!record) return;
  for (const [key, child] of Object.entries(record)) {
    countPrivacyResiduals(key, stats);
    countPrivacyResiduals(child, stats);
  }
}

function sha256Text(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function sha256File(filePath: string): string {
  return createHash("sha256").update(readFileSync(filePath)).digest("hex");
}

function safeRef(value: string): string {
  return `sha256:${sha256Text(value).slice(0, 16)}`;
}

function defaultScenarioNativePrivacyAttestationPath(outPath: string): string {
  return outPath.endsWith(".jsonl")
    ? `${outPath.slice(0, -".jsonl".length)}.privacy-attestation.json`
    : `${outPath}.privacy-attestation.json`;
}

export function rowPrivacyAttestation(
  attestationPath: string,
  passed: boolean,
): NativeRowPrivacyAttestation {
  return {
    schema: SCENARIO_NATIVE_PRIVACY_ATTESTATION_SCHEMA,
    version: SCENARIO_NATIVE_PRIVACY_ATTESTATION_VERSION,
    source: "scenario_native_export",
    redacted: true,
    // Reflect the REAL gate result, not a hardcoded `true` (#13623): a row that
    // still carries an unredacted residual after filtering has NOT truthfully
    // passed review, so it must not stamp reviewed/passed:true.
    reviewed: passed,
    passed,
    attestationPath: path.basename(attestationPath),
  };
}

/**
 * Redact every row's PII in place and return the redacted rows. Residual
 * counting (which determines the gate result) runs AFTER this over the redacted
 * rows; the per-row privacy-attestation marker is stamped by
 * {@link stampRowPrivacyAttestations} once the real pass/fail is known, so a
 * row can't claim `passed:true` while carrying an unredacted residual (#13623).
 */
function redactNativeBoundaryRows(
  rows: NativeBoundaryRow[],
  stats: PrivacyFilterStats,
): NativeBoundaryRow[] {
  return rows.map((row) => filterPrivacyValue(row, stats) as NativeBoundaryRow);
}

/**
 * Stamp the per-row privacy-attestation marker with the REAL gate result after
 * residual counting has determined pass/fail. Mutates the rows in place.
 */
function stampRowPrivacyAttestations(
  rows: NativeBoundaryRow[],
  attestationPath: string,
  passed: boolean,
): void {
  const marker = rowPrivacyAttestation(attestationPath, passed);
  for (const row of rows) {
    row.privacyAttestation = marker;
    row.metadata = {
      ...(toRecord(row.metadata) ?? {}),
      privacy_attestation: marker,
    };
  }
}

function privacyCategories(
  stats: PrivacyFilterStats,
): Record<PrivacyCategory, number> {
  const out = {} as Record<PrivacyCategory, number>;
  for (const category of PRIVACY_CATEGORIES) {
    out[category] = stats.redactionsByCategory[category] ?? 0;
  }
  return out;
}

function buildScenarioNativePrivacyAttestation(params: {
  jsonlPath: string;
  runDir: string;
  trajectoriesDir: string;
  rows: number;
  stats: PrivacyFilterStats;
}): ScenarioNativePrivacyAttestation {
  const categories = privacyCategories(params.stats);
  const residual_findings = {
    count: params.stats.residualTotal,
    by_label: { ...params.stats.residualByLabel },
  };
  const passed = params.stats.residualTotal === 0;
  const input_path_refs = [
    safeRef(params.runDir),
    safeRef(params.trajectoriesDir),
  ];
  return {
    schema: SCENARIO_NATIVE_PRIVACY_ATTESTATION_SCHEMA,
    version: SCENARIO_NATIVE_PRIVACY_ATTESTATION_VERSION,
    generated_at: new Date().toISOString(),
    passed,
    strict: true,
    // Scenario data is SYNTHETIC, not a reviewed real-user export (#13623):
    // label it truthfully so it can't be waved through a privacy gate as if it
    // were real-user data.
    sourceKind: SCENARIO_NATIVE_SOURCE_KIND,
    source: {
      kind: SCENARIO_NATIVE_SOURCE_KIND,
      realUserExport: false,
      inputPathRefs: input_path_refs,
    },
    privacy: {
      reviewed: passed,
      realUserExport: false,
      attestationType: "privacy_filter",
    },
    input_count: params.rows,
    output_count: params.rows,
    redaction_count: params.stats.redactionsTotal,
    categories,
    residual_findings,
    residual_findings_count: params.stats.residualTotal,
    input_path_refs,
    artifacts: {
      redacted_jsonl: {
        path: path.basename(params.jsonlPath),
        path_ref: safeRef(params.jsonlPath),
        sha256: sha256File(params.jsonlPath),
        rows: params.rows,
      },
    },
    gate: {
      passed,
      strict: true,
      sourceKind: SCENARIO_NATIVE_SOURCE_KIND,
      input_count: params.rows,
      output_count: params.rows,
      redaction_count: params.stats.redactionsTotal,
      categories,
      residual_findings,
      residual_findings_count: params.stats.residualTotal,
    },
  };
}

function isRecordedTrajectory(value: unknown): value is RecordedTrajectory {
  const record = toRecord(value);
  return (
    record !== null &&
    typeof record.trajectoryId === "string" &&
    typeof record.agentId === "string" &&
    Array.isArray(record.stages)
  );
}

function normalizeTaskToken(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase()
    .replace(/[^a-z0-9:_-]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");
}

function recordedModelSearchText(model: RecordedModelCall | undefined): string {
  if (!model) return "";
  const parts = [
    model.prompt,
    typeof model.messages === "undefined"
      ? undefined
      : JSON.stringify(model.messages),
    model.response,
    model.modelType,
    model.modelName,
    model.provider,
  ];
  return parts
    .filter((part): part is string => typeof part === "string")
    .join("\n");
}

function inferLifeOpsTaskType(
  kind: string | undefined,
  model: RecordedModelCall | undefined,
): string | null {
  const normalized = normalizeTaskToken(
    `${kind ?? ""}\n${recordedModelSearchText(model)}`,
  );
  for (const task of LIFEOPS_NATIVE_TASKS) {
    if (normalized.includes(task)) return task;
  }

  const text = recordedModelSearchText(model).toLowerCase();
  if (
    text.includes("plan the calendar action for this request") ||
    text.includes("subactions[7]{name,use}")
  ) {
    return "calendar_extract";
  }
  if (
    text.includes("plan the scheduling negotiation action for this request")
  ) {
    return "schedule_plan";
  }
  if (text.includes("current reminder:") && text.includes("reminder text:")) {
    return "reminder_dispatch";
  }
  if (text.includes("owner's morning briefing")) {
    return "morning_brief";
  }
  if (text.includes("triage one inbox item")) {
    return "inbox_triage";
  }
  if (text.includes("prebrief for an upcoming meeting")) {
    return "meeting_prep";
  }
  if (text.includes("health/sleep check-in")) {
    return "health_checkin";
  }
  if (text.includes("screen-time") && text.includes("focus adjustment")) {
    return "screentime_recap";
  }
  return null;
}

function inferOrchestratorTaskType(
  kind: string | undefined,
  model: RecordedModelCall | undefined,
): string | null {
  const normalized = normalizeTaskToken(
    `${kind ?? ""}\n${recordedModelSearchText(model)}`,
  );
  for (const task of ORCHESTRATOR_NATIVE_TASKS) {
    if (normalized.includes(task)) return task;
  }

  const text = recordedModelSearchText(model).toLowerCase();
  if (
    text.includes(
      "final sign-off on a coding sub-agent's work before the parent agent marks the task done",
    ) &&
    text.includes("acceptance criteria") &&
    text.includes("completion evidence collected for the sub-agent")
  ) {
    return "goal_verification";
  }
  return null;
}

function lifeOpsDomainForTask(taskType: string): string | undefined {
  if (!LIFEOPS_NATIVE_TASK_SET.has(taskType)) return undefined;
  return taskType === "health_checkin" || taskType === "screentime_recap"
    ? "health"
    : "lifeops";
}

function domainForTask(taskType: string): string | undefined {
  const lifeOpsDomain = lifeOpsDomainForTask(taskType);
  if (lifeOpsDomain) return lifeOpsDomain;
  if (ORCHESTRATOR_NATIVE_TASK_SET.has(taskType)) return "agent-orchestrator";
  return undefined;
}

function stageKindToTaskType(
  kind: string | undefined,
  modelType: string | undefined,
  model?: RecordedModelCall,
): string {
  const orchestratorTask = inferOrchestratorTaskType(kind, model);
  if (orchestratorTask) return orchestratorTask;

  const lifeOpsTask = inferLifeOpsTaskType(kind, model);
  if (lifeOpsTask) return lifeOpsTask;

  const tokens = `${kind ?? ""} ${modelType ?? ""}`
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase();
  if (tokens.includes("planner")) return "action_planner";
  if (tokens.includes("message_handler") || tokens.includes("should_respond")) {
    return "should_respond";
  }
  if (tokens.includes("evaluation") || tokens.includes("evaluator"))
    return "evaluation";
  if (tokens.includes("facts") || tokens.includes("relationships"))
    return "facts_and_relationships";
  return "response";
}

function normalizeToolCalls(
  toolCalls: RecordedModelCall["toolCalls"],
):
  | Array<{ toolCallId?: string; toolName: string; input: unknown }>
  | undefined {
  if (!Array.isArray(toolCalls) || toolCalls.length === 0) return undefined;
  const out: Array<{ toolCallId?: string; toolName: string; input: unknown }> =
    [];
  for (const call of toolCalls) {
    const record = toRecord(call);
    if (!record) continue;
    const name = typeof record.name === "string" ? record.name.trim() : "";
    if (!name) continue;
    const entry: { toolCallId?: string; toolName: string; input: unknown } = {
      toolName: name,
      input: toRecord(record.args) ?? {},
    };
    if (typeof record.id === "string" && record.id.length > 0)
      entry.toolCallId = record.id;
    out.push(entry);
  }
  return out.length > 0 ? out : undefined;
}

function buildRequest(model: RecordedModelCall): NativeBoundaryRow["request"] {
  const request: NativeBoundaryRow["request"] = {};
  const messages = Array.isArray(model.messages) ? model.messages : undefined;
  if (messages && messages.length > 0) {
    request.messages = messages;
  } else if (typeof model.prompt === "string" && model.prompt.length > 0) {
    request.prompt = model.prompt;
  }
  if (model.tools !== undefined) request.tools = model.tools;
  if (model.toolChoice !== undefined) request.toolChoice = model.toolChoice;
  if (model.providerOptions !== undefined)
    request.providerOptions = model.providerOptions;
  return request;
}

function buildResponse(
  model: RecordedModelCall,
): NativeBoundaryRow["response"] {
  const response: NativeBoundaryRow["response"] = {
    text: typeof model.response === "string" ? model.response : "",
  };
  const toolCalls = normalizeToolCalls(model.toolCalls);
  if (toolCalls) response.toolCalls = toolCalls;
  if (typeof model.finishReason === "string")
    response.finishReason = model.finishReason;
  const usage = model.usage;
  if (usage) {
    const out: NonNullable<NativeBoundaryRow["response"]["usage"]> = {};
    if (typeof usage.promptTokens === "number")
      out.promptTokens = usage.promptTokens;
    if (typeof usage.completionTokens === "number")
      out.completionTokens = usage.completionTokens;
    if (typeof usage.totalTokens === "number")
      out.totalTokens = usage.totalTokens;
    if (typeof usage.cacheReadInputTokens === "number") {
      out.cacheReadInputTokens = usage.cacheReadInputTokens;
    }
    if (typeof usage.cacheCreationInputTokens === "number") {
      out.cacheCreationInputTokens = usage.cacheCreationInputTokens;
    }
    if (Object.keys(out).length > 0) response.usage = out;
  }
  return response;
}

/**
 * Convert one recorded scenario trajectory into the model-boundary rows that
 * `eliza_native_v1` defines — one row per `stages[].model` call. Stages without
 * a model call (tool execution, tool search, cache snapshots) are skipped:
 * they are not training-supervision boundaries.
 */
export function recordedTrajectoryToNativeRows(
  trajectory: RecordedTrajectory,
  scenarioOutcome?: ScenarioOutcome,
  judgeScore?: number,
  tier?: string,
): NativeBoundaryRow[] {
  const rows: NativeBoundaryRow[] = [];
  const stages: RecordedStage[] = Array.isArray(trajectory.stages)
    ? trajectory.stages
    : [];
  for (const [stepIndex, stage] of stages.entries()) {
    const model = stage?.model;
    if (!model || typeof model !== "object") continue;
    const request = buildRequest(model);
    const response = buildResponse(model);
    const hasRequest =
      (Array.isArray(request.messages) && request.messages.length > 0) ||
      (typeof request.prompt === "string" && request.prompt.length > 0);
    const hasResponse =
      response.text.trim().length > 0 || (response.toolCalls?.length ?? 0) > 0;
    if (!hasRequest || !hasResponse) continue;

    const stepId =
      typeof stage.stageId === "string" && stage.stageId.length > 0
        ? stage.stageId
        : `${trajectory.trajectoryId}:stage:${stepIndex + 1}`;
    const callId = `${trajectory.trajectoryId}:${stepId}`;
    const scenarioId =
      typeof trajectory.scenarioId === "string" &&
      trajectory.scenarioId.length > 0
        ? trajectory.scenarioId
        : null;
    const taskType = stageKindToTaskType(stage.kind, model.modelType, model);
    const taskDomain = domainForTask(taskType);
    rows.push({
      format: NATIVE_FORMAT,
      schemaVersion: NATIVE_SCHEMA_VERSION,
      boundary: GENERATE_TEXT_BOUNDARY,
      ...(scenarioOutcome ? { scenarioStatus: scenarioOutcome } : {}),
      ...(judgeScore !== undefined ? { judgeScore } : {}),
      ...(tier ? { tier } : {}),
      request,
      response,
      trajectoryId: trajectory.trajectoryId,
      agentId: trajectory.agentId,
      scenarioId,
      batchId: null,
      stepId,
      callId,
      stepIndex,
      callIndex: 0,
      timestamp:
        typeof stage.startedAt === "number" && Number.isFinite(stage.startedAt)
          ? stage.startedAt
          : (trajectory.startedAt ?? 0),
      purpose: stage.kind,
      stepType: stage.kind,
      model: typeof model.modelName === "string" ? model.modelName : undefined,
      modelVersion:
        typeof model.modelName === "string" ? model.modelName : undefined,
      modelType:
        typeof model.modelType === "string" ? model.modelType : undefined,
      provider: typeof model.provider === "string" ? model.provider : undefined,
      metadata: {
        task_type: taskType,
        ...(taskDomain ? { domain: taskDomain } : {}),
        source_dataset: "scenario_trajectory_boundary",
        trajectory_id: trajectory.trajectoryId,
        step_id: stepId,
        call_id: callId,
        agent_id: trajectory.agentId,
        ...(typeof trajectory.runId === "string" && trajectory.runId.length > 0
          ? { source_run_id: trajectory.runId }
          : {}),
        ...(typeof trajectory.roomId === "string" &&
        trajectory.roomId.length > 0
          ? { source_room_id: trajectory.roomId }
          : {}),
        ...(scenarioId ? { scenario_id: scenarioId } : {}),
        source_stage_kind: stage.kind,
        ...(typeof stage.iteration === "number"
          ? { source_stage_iteration: stage.iteration }
          : {}),
        source_model:
          typeof model.modelName === "string" ? model.modelName : undefined,
        source_model_type:
          typeof model.modelType === "string" ? model.modelType : undefined,
        source_provider:
          typeof model.provider === "string" ? model.provider : undefined,
        trajectory_status: trajectory.status,
        ...(scenarioOutcome ? { scenario_status: scenarioOutcome } : {}),
        ...(judgeScore !== undefined ? { judge_score: judgeScore } : {}),
        ...(tier ? { tier } : {}),
        ...(typeof model.costUsd === "number"
          ? { source_cost_usd: model.costUsd }
          : {}),
      },
    });
  }
  return rows;
}

function collectTrajectoryFiles(rootDir: string): string[] {
  const out: string[] = [];
  const stack = [rootDir];
  while (stack.length > 0) {
    const dir = stack.pop();
    if (!dir) continue;
    let entries: import("node:fs").Dirent[];
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
        continue;
      }
      if (
        entry.isFile() &&
        entry.name.endsWith(".json") &&
        !entry.name.endsWith(".tmp")
      ) {
        out.push(full);
      }
    }
  }
  return out.sort();
}

function defaultScenarioNativeManifestPath(outPath: string): string {
  return outPath.endsWith(".jsonl")
    ? `${outPath.slice(0, -".jsonl".length)}.manifest.json`
    : `${outPath}.manifest.json`;
}

function addString(set: Set<string>, value: unknown): void {
  if (typeof value === "string" && value.trim().length > 0) {
    set.add(value.trim());
  }
}

/**
 * Read every `RecordedTrajectory` JSON under `<runDir>/trajectories/` and write
 * the converted `eliza_native_v1` rows as JSONL to `outPath`. Returns the
 * number of rows written. Trajectory files that fail to parse or aren't
 * recorded-trajectory shaped are skipped with a warning — a malformed file in
 * the run directory should not block the rest of the export.
 *
 * `scenarioOutcomes` maps scenario id → assertion outcome (passed/failed/
 * skipped). Each emitted row carries its scenario outcome as `scenarioStatus`
 * and `metadata.scenario_status` so the training prep scorer routes failed or
 * skipped trajectories to rating="repair"/weight=0 instead of stamping them
 * gold. Without this map the exporter cannot tell a scenario that mechanically
 * finished but failed its assertions from a genuinely passing one — and would
 * export both as gold.
 *
 * `scenarioJudgeScores` maps scenario id → numeric judge score
 * (`ScenarioReport.judgeScore`). When present, each row carries it as
 * `judgeScore` and `metadata.judge_score` so training prep can reward-weight
 * rows on judged quality, not just pass/fail (#8795).
 */
export function exportScenarioNativeJsonl(
  runDir: string,
  outPath: string,
  scenarioOutcomes?: ScenarioOutcomeMap,
  scenarioJudgeScores?: ScenarioJudgeScoreMap,
  scenarioTiers?: ScenarioTierMap,
): number {
  const trajectoriesDir = path.join(runDir, "trajectories");
  const files = collectTrajectoryFiles(trajectoriesDir);
  const rawRows: NativeBoundaryRow[] = [];
  const runIds = new Set<string>();
  const scenarioIds = new Set<string>();
  const agentIds = new Set<string>();
  let parsedTrajectories = 0;
  let skippedFiles = 0;
  for (const file of files) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(readFileSync(file, "utf-8"));
    } catch (err) {
      skippedFiles += 1;
      logger.warn(
        `[scenario-runner] skipping unparseable trajectory file ${file}: ${err instanceof Error ? err.message : String(err)}`,
      );
      continue;
    }
    if (!isRecordedTrajectory(parsed)) {
      skippedFiles += 1;
      logger.warn(
        `[scenario-runner] skipping non-trajectory JSON file ${file} (no trajectoryId/agentId/stages)`,
      );
      continue;
    }
    parsedTrajectories += 1;
    addString(runIds, parsed.runId);
    addString(scenarioIds, parsed.scenarioId);
    addString(agentIds, parsed.agentId);
    const scenarioOutcome =
      scenarioOutcomes && typeof parsed.scenarioId === "string"
        ? scenarioOutcomes.get(parsed.scenarioId)
        : undefined;
    if (
      scenarioOutcomes &&
      !scenarioOutcome &&
      typeof parsed.scenarioId === "string"
    ) {
      logger.warn(
        `[scenario-runner] trajectory ${parsed.trajectoryId} has scenarioId="${parsed.scenarioId}" with no matching scenario report; exporting without a pass/fail status`,
      );
    }
    const judgeScore =
      scenarioJudgeScores && typeof parsed.scenarioId === "string"
        ? scenarioJudgeScores.get(parsed.scenarioId)
        : undefined;
    const tier =
      scenarioTiers && typeof parsed.scenarioId === "string"
        ? scenarioTiers.get(parsed.scenarioId)
        : undefined;
    rawRows.push(
      ...recordedTrajectoryToNativeRows(
        parsed,
        scenarioOutcome,
        judgeScore,
        tier,
      ),
    );
  }
  mkdirSync(path.dirname(outPath), { recursive: true });
  const privacyAttestationPath =
    defaultScenarioNativePrivacyAttestationPath(outPath);
  const privacyStats = newPrivacyFilterStats();
  const rows = redactNativeBoundaryRows(rawRows, privacyStats);
  // Count residuals on the redacted rows FIRST (before stamping the marker), so
  // the gate result reflects genuine leftover PII and the marker text can't
  // pollute the residual scan.
  for (const row of rows) countPrivacyResiduals(row, privacyStats);
  // The gate passes only when no residual survived filtering; stamp every row's
  // privacy attestation with that REAL result instead of a hardcoded true so an
  // unredacted residual propagates passed:false to the rows (#13623).
  const gatePassed = privacyStats.residualTotal === 0;
  stampRowPrivacyAttestations(rows, privacyAttestationPath, gatePassed);
  const body =
    rows.length === 0
      ? ""
      : `${rows.map((row) => JSON.stringify(row)).join("\n")}\n`;
  writeFileSync(outPath, body, "utf-8");
  const privacyAttestation = buildScenarioNativePrivacyAttestation({
    jsonlPath: outPath,
    runDir,
    trajectoriesDir,
    rows: rows.length,
    stats: privacyStats,
  });
  writeFileSync(
    privacyAttestationPath,
    `${JSON.stringify(privacyAttestation, null, 2)}\n`,
    "utf-8",
  );
  let passedRows = 0;
  let failedRows = 0;
  let skippedScenarioRows = 0;
  let unknownOutcomeRows = 0;
  for (const row of rows) {
    if (row.scenarioStatus === "passed") passedRows += 1;
    else if (row.scenarioStatus === "failed") failedRows += 1;
    else if (row.scenarioStatus === "skipped") skippedScenarioRows += 1;
    else unknownOutcomeRows += 1;
  }
  const manifestPath = defaultScenarioNativeManifestPath(outPath);
  const manifest: ScenarioNativeExportManifest = {
    schema: SCENARIO_NATIVE_EXPORT_SCHEMA,
    schemaVersion: SCENARIO_NATIVE_EXPORT_VERSION,
    generatedAt: new Date().toISOString(),
    runDir,
    trajectoriesDir,
    jsonlPath: outPath,
    manifestPath,
    privacyAttestationPath,
    counts: {
      trajectoryFiles: files.length,
      parsedTrajectories,
      skippedFiles,
      rows: rows.length,
      passedRows,
      failedRows,
      skippedScenarioRows,
      unknownOutcomeRows,
    },
    runIds: [...runIds].sort(),
    scenarioIds: [...scenarioIds].sort(),
    agentIds: [...agentIds].sort(),
    privacy: {
      reviewed: privacyAttestation.passed,
      attestationSchema: SCENARIO_NATIVE_PRIVACY_ATTESTATION_SCHEMA,
      attestationVersion: SCENARIO_NATIVE_PRIVACY_ATTESTATION_VERSION,
      attestationPath: privacyAttestationPath,
      redactions: privacyStats.redactionsTotal,
      residualFindings: privacyStats.residualTotal,
      categories: privacyCategories(privacyStats),
    },
  };
  writeFileSync(
    manifestPath,
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf-8",
  );
  logger.info(
    `[scenario-runner] wrote ${rows.length} redacted eliza_native_v1 row(s) from ${files.length} trajectory file(s) → ${outPath} (passed=${passedRows} failed=${failedRows} skipped=${skippedScenarioRows} unknown=${unknownOutcomeRows} redactions=${privacyStats.redactionsTotal} residuals=${privacyStats.residualTotal}) (manifest → ${manifestPath}; privacy attestation → ${privacyAttestationPath})`,
  );
  return rows.length;
}
