/**
 * Table DDL for the tier-upgrade single-flight PGlite suites, mirroring the
 * Drizzle schemas the flows read and write (organizations, users,
 * user_characters, agent_sandboxes, api_keys, jobs). Executed as plain
 * statements instead of drizzle-kit `pushSchema` because drizzle-kit reacts to
 * internal errors with a silent `process.exit(1)`, which kills the whole
 * multi-file `bun test` process the coverage lane runs changed suites in
 * (#15943). Column lists were introspected from a real `pushSchema` apply;
 * every column of each Drizzle schema must exist here or `select()` fails
 * loudly with "column does not exist" — extend this file alongside any schema
 * change. Foreign keys are intentionally omitted (same as the harness in
 * `db/repositories/__tests__/jobs-recovery.test.ts`): the suites exercise
 * service invariants, not referential constraints.
 */

export const TIER_UPGRADE_TEST_TABLES: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS "organizations" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "credit_balance" numeric(12,6) NOT NULL DEFAULT 0.000000,
  "settings" jsonb DEFAULT '{}'::jsonb,
  "stripe_customer_id" text,
  "billing_email" text,
  "stripe_payment_method_id" text,
  "stripe_default_payment_method" text,
  "auto_top_up_enabled" boolean DEFAULT false,
  "auto_top_up_threshold" numeric(10,2),
  "auto_top_up_amount" numeric(10,2),
  "pay_as_you_go_from_earnings" boolean NOT NULL DEFAULT true,
  "steward_tenant_id" text,
  "steward_tenant_api_key" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "email" text,
  "email_verified" boolean DEFAULT false,
  "wallet_address" text,
  "wallet_chain_type" text,
  "wallet_verified" boolean NOT NULL DEFAULT false,
  "name" text,
  "avatar" text,
  "organization_id" uuid,
  "role" text NOT NULL DEFAULT 'member'::text,
  "steward_user_id" text NOT NULL,
  "telegram_id" text,
  "telegram_username" text,
  "telegram_first_name" text,
  "telegram_photo_url" text,
  "discord_id" text,
  "discord_username" text,
  "discord_global_name" text,
  "discord_avatar_url" text,
  "whatsapp_id" text,
  "whatsapp_name" text,
  "phone_number" text,
  "phone_verified" boolean DEFAULT false,
  "is_anonymous" boolean NOT NULL DEFAULT false,
  "anonymous_session_id" text,
  "expires_at" timestamp,
  "nickname" text,
  "work_function" text,
  "preferences" text,
  "email_notifications" boolean DEFAULT true,
  "response_notifications" boolean DEFAULT true,
  "is_active" boolean NOT NULL DEFAULT true,
  "email_ciphertext" text,
  "email_nonce" text,
  "email_auth_tag" text,
  "email_kms_key_id" text,
  "email_kms_key_version" integer,
  "email_blind_index" text,
  "phone_ciphertext" text,
  "phone_nonce" text,
  "phone_auth_tag" text,
  "phone_kms_key_id" text,
  "phone_kms_key_version" integer,
  "phone_blind_index" text,
  "wallet_address_ciphertext" text,
  "wallet_address_nonce" text,
  "wallet_address_auth_tag" text,
  "wallet_address_kms_key_id" text,
  "wallet_address_kms_key_version" integer,
  "wallet_address_blind_index" text,
  "telegram_id_ciphertext" text,
  "telegram_id_nonce" text,
  "telegram_id_auth_tag" text,
  "telegram_id_kms_key_id" text,
  "telegram_id_kms_key_version" integer,
  "discord_id_ciphertext" text,
  "discord_id_nonce" text,
  "discord_id_auth_tag" text,
  "discord_id_kms_key_id" text,
  "discord_id_kms_key_version" integer,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "deleted_at" timestamp,
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "user_characters" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "name" text NOT NULL,
  "username" text,
  "system" text,
  "bio" jsonb NOT NULL,
  "message_examples" jsonb DEFAULT '[]'::jsonb,
  "post_examples" jsonb DEFAULT '[]'::jsonb,
  "topics" jsonb DEFAULT '[]'::jsonb,
  "adjectives" jsonb DEFAULT '[]'::jsonb,
  "knowledge" jsonb DEFAULT '[]'::jsonb,
  "plugins" jsonb DEFAULT '[]'::jsonb,
  "settings" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "secrets" jsonb DEFAULT '{}'::jsonb,
  "style" jsonb DEFAULT '{}'::jsonb,
  "character_data" jsonb NOT NULL,
  "is_template" boolean NOT NULL DEFAULT false,
  "is_public" boolean NOT NULL DEFAULT false,
  "avatar_url" text,
  "category" text,
  "tags" jsonb DEFAULT '[]'::jsonb,
  "featured" boolean NOT NULL DEFAULT false,
  "view_count" integer NOT NULL DEFAULT 0,
  "interaction_count" integer NOT NULL DEFAULT 0,
  "popularity_score" integer NOT NULL DEFAULT 0,
  "source" text NOT NULL DEFAULT 'cloud'::text,
  "token_address" text,
  "token_chain" text,
  "token_name" text,
  "token_ticker" text,
  "erc8004_registered" boolean NOT NULL DEFAULT false,
  "erc8004_network" text,
  "erc8004_agent_id" integer,
  "erc8004_agent_uri" text,
  "erc8004_tx_hash" text,
  "erc8004_registered_at" timestamp,
  "monetization_enabled" boolean NOT NULL DEFAULT false,
  "inference_markup_percentage" numeric(7,2) NOT NULL DEFAULT 0.00,
  "payout_wallet_address" text,
  "total_inference_requests" integer NOT NULL DEFAULT 0,
  "total_creator_earnings" numeric(12,4) NOT NULL DEFAULT 0.0000,
  "total_platform_revenue" numeric(12,4) NOT NULL DEFAULT 0.0000,
  "a2a_enabled" boolean NOT NULL DEFAULT true,
  "mcp_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "agent_sandboxes" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "character_id" uuid,
  "sandbox_id" text,
  "status" text NOT NULL DEFAULT 'pending'::text,
  "execution_tier" text NOT NULL DEFAULT 'shared'::text,
  "bridge_url" text,
  "health_url" text,
  "agent_name" text,
  "agent_config" jsonb,
  "database_uri" text,
  "database_status" text NOT NULL DEFAULT 'none'::text,
  "database_error" text,
  "snapshot_id" text,
  "last_backup_at" timestamptz,
  "last_heartbeat_at" timestamptz,
  "error_message" text,
  "error_count" integer NOT NULL DEFAULT 0,
  "environment_vars" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "node_id" text,
  "container_name" text,
  "bridge_port" integer,
  "web_ui_port" integer,
  "headscale_ip" text,
  "docker_image" text,
  "image_digest" text,
  "previous_image_digest" text,
  "previous_docker_image" text,
  "billing_status" text NOT NULL DEFAULT 'active'::text,
  "last_billed_at" timestamptz,
  "hourly_rate" numeric(10,4) DEFAULT 0.0100,
  "total_billed" numeric(10,2) NOT NULL DEFAULT 0.00,
  "shutdown_warning_sent_at" timestamptz,
  "scheduled_shutdown_at" timestamptz,
  "pool_status" text,
  "pool_ready_at" timestamptz,
  "claimed_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "deleted_at" timestamptz,
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "api_keys" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "name" text NOT NULL,
  "description" text,
  "key_hash" text NOT NULL,
  "key_prefix" text NOT NULL,
  "key_ciphertext" text,
  "key_nonce" text,
  "key_auth_tag" text,
  "key_kms_key_id" text,
  "key_kms_key_version" integer,
  "organization_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "rate_limit" integer NOT NULL DEFAULT 1000,
  "is_active" boolean NOT NULL DEFAULT true,
  "usage_count" integer NOT NULL DEFAULT 0,
  "expires_at" timestamp,
  "last_used_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "deleted_at" timestamp,
  PRIMARY KEY ("id")
)`,
  `CREATE TABLE IF NOT EXISTS "jobs" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "type" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending'::text,
  "data" jsonb NOT NULL,
  "data_storage" text NOT NULL DEFAULT 'inline'::text,
  "data_key" text,
  "agent_id" text,
  "character_id" text,
  "result" jsonb,
  "result_storage" text NOT NULL DEFAULT 'inline'::text,
  "result_key" text,
  "error" text,
  "error_storage" text NOT NULL DEFAULT 'inline'::text,
  "error_key" text,
  "attempts" integer NOT NULL DEFAULT 0,
  "max_attempts" integer NOT NULL DEFAULT 3,
  "organization_id" uuid NOT NULL,
  "user_id" uuid,
  "api_key_id" uuid,
  "generation_id" uuid,
  "webhook_url" text,
  "webhook_status" text,
  "estimated_completion_at" timestamp,
  "scheduled_for" timestamp NOT NULL DEFAULT now(),
  "started_at" timestamp,
  "completed_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
)`,
];
