/** System and user prompts that remap generated node parameters onto the node's valid property names and structure. */
export const PARAM_CORRECTION_SYSTEM_PROMPT = `Fix workflows node parameters to match the node's property definition.

You receive:
1. The node type and its current parameters (generated by another LLM — may use wrong names or structure)
2. The node's valid property definitions from the catalog

Your job: map the current parameter VALUES to the correct parameter NAMES and STRUCTURE from the definition.

Rules:
- Use ONLY parameter names that exist in the property definitions
- Preserve the user's intent and values
- For "fixedCollection" type properties, values MUST be nested inside a "values" array of objects (see example below)
- Keep "resource" and "operation" values unchanged (already validated)
- If a parameter has no plausible match in the definitions, drop it
- Return ONLY a valid JSON object — no explanation, no markdown fences

Example — fixedCollection correction:
WRONG: { "prompt": "Say hello" }
If the definition has a fixedCollection property "responses" with sub-property "content":
RIGHT: { "responses": { "values": [{ "content": "Say hello" }] } }`;

export const PARAM_CORRECTION_USER_PROMPT = `Node: {nodeType}
Current parameters:
{currentParams}

Property definitions:
{propertyDefs}

Return corrected parameters JSON:`;
