/** Implements Electrobun surface remote event types ts boundaries for desktop app-core. */
export type {
  FileListParams,
  FileListResult,
  FileReadTextParams,
  FileReadTextResult,
  FileRoot,
  FileSearchParams,
  FileSearchResult,
  FileStat,
  FileWriteTextParams,
  FileWriteTextResult,
} from "../../../fs/src/bun/protocol.ts";
export type {
  GitAddParams,
  GitBranch,
  GitBranchCreateParams,
  GitBranchDeleteParams,
  GitCheckoutParams,
  GitCommandResult,
  GitCommandRunParams,
  GitCommitParams,
  GitDiffParams,
  GitLogEntry,
  GitLogParams,
  GitOperation,
  GitRemote,
  GitRemoteOperationParams,
  GitRepoInfo,
  GitRepoParams,
  GitRestoreParams,
  GitStatusPayload,
  GitStatusResult,
} from "../../../git/src/bun/protocol.ts";
export type {
  Eliza1BundleTier,
  Eliza1VoiceComponent,
  LocalModelActiveSnapshot,
  LocalModelCatalogEntry,
  LocalModelDownloadJob,
  LocalModelEmbeddingParams,
  LocalModelEmbeddingResult,
  LocalModelGenerateParams,
  LocalModelGenerateResult,
  LocalModelHardwareSnapshot,
  LocalModelHubSnapshot,
  LocalModelInstalledEntry,
} from "../../../local-model/src/bun/protocol.ts";
export type {
  PtyCommandRunParams,
  PtyCommandRunResult,
  PtyCreateSessionParams,
  PtyCreateSessionResult,
  PtyKillParams,
  PtyOutputEntry,
  PtyOutputTailParams,
  PtyOutputTailResult,
  PtyResizeParams,
  PtySession,
  PtyStatus,
  PtyWriteParams,
} from "../../../pty/src/bun/protocol.ts";
export type {
  AgentMessageParams,
  AgentMessageResult,
  AgentMessageStreamEvent,
  AgentMessageStreamParams,
  AgentMessageStreamStartResult,
  AgentMessageStreamStatus,
  AgentSummary,
  ApiBridgeError,
  ApiDiscoveryResult,
  ConversationSummary,
  RuntimeEventName,
  RuntimeEventPayload,
  RuntimeLogEntry as LogEntry,
  RuntimeState,
  RuntimeWorkerRequestMessage,
  RuntimeWorkerResponseMessage,
  StreamingRouteStatus,
} from "../../../runtime/src/bun/protocol.ts";
